export type LabelPair = {
  id: number;
  before: string;
  after: string;
};

export type NormCard = {
  id: string;
  type: string;
  ac: string;
  bg1: string;
  bg2: string;
  b: string;
  a: string;
  tags: string[];
};

export const labelPairs: LabelPair[] = [
  { id: 0, before: "What we knew", after: "What we swallowed" },
  { id: 1, before: "Used to be", after: "Now it's called" },
  { id: 2, before: "The old script", after: "The rewrite" },
  { id: 3, before: "Once upon a time", after: "Plot twist" },
  { id: 4, before: "Before the memo", after: "After the spin" },
];

export const DEFAULT_LABEL_INDEX = 3;

export const cards: NormCard[] = [
  {
    id: "corporate",
    type: "corporate",
    ac: "#2FCCAA",
    bg1: "#0b1310",
    bg2: "#101a16",
    b: "Work had edges. You finished at five and the rest of the day was yours. Missing a call after hours was a coincidence, not a character flaw.",
    a: "Replying at midnight is called ownership. Logging off on time means you're not committed. The office relocated to your phone and hasn't moved since.",
    tags: ["#corporate", "#urgent", "#burnout", "#serious"],
  },
  {
    id: "economic",
    type: "economic",
    ac: "#EF9F27",
    bg1: "#120d00",
    bg2: "#1a1408",
    b: "Debt was a sign something had gone terribly wrong. You borrowed when the floor fell out - not as the standard opening chapter of becoming an adult.",
    a: "Student loan, home loan, car loan - you are welcomed into society already in repayment. Responsibility was redefined as the ability to manage what you owe.",
    tags: ["#economic", "#dystopian", "#urgent", "#inequality"],
  },
  {
    id: "social",
    type: "social",
    ac: "#9B8FE8",
    bg1: "#0c0a16",
    bg2: "#111020",
    b: "Being alone was just solitude. You could sit somewhere and simply be there. Boredom was a pause in the day, not a condition to immediately treat.",
    a: "Surrounded by thousands and calling it connected. Scrolling through fifty lives in sixty seconds without touching a single one. Presence became a status indicator.",
    tags: ["#social", "#melancholy", "#ironic", "#silent"],
  },
  {
    id: "health",
    type: "health",
    ac: "#D85A30",
    bg1: "#110600",
    bg2: "#180e06",
    b: "Sleep was just what bodies needed. Nobody wore exhaustion as a badge or announced how little rest they had as evidence of effort and worth.",
    a: "Sleeping four hours and still showing up is called discipline. Exhaustion became the currency of credibility. Rest was quietly rebranded as a lack of ambition.",
    tags: ["#health", "#darkhumor", "#serious", "#burnout"],
  },
  {
    id: "privacy",
    type: "privacy",
    ac: "#38BDF8",
    bg1: "#041018",
    bg2: "#081520",
    b: "Privacy was the default. You walked through a day and nobody catalogued where you went, what you looked at, or what you might want to buy next.",
    a: "Every search, click, location, and hesitation is recorded, profiled, and sold. Opting out is a premium feature. Being watched became the price of using the internet.",
    tags: ["#privacy", "#tech", "#dystopian", "#urgent"],
  },
  {
    id: "food",
    type: "food",
    ac: "#84CC16",
    bg1: "#071000",
    bg2: "#0d1800",
    b: "Food was just food. You ate what was grown or made, got full, and moved on. The idea of eating something engineered to prevent you from stopping hadn't quite arrived.",
    a: "Ultra-processed food engineers your cravings, then the same economy sells you supplements to undo the damage. The system profits on both ends - you pay to get sick, then pay to recover.",
    tags: ["#food", "#darkhumor", "#health", "#ironic"],
  },
  {
    id: "culture",
    type: "culture",
    ac: "#F43F5E",
    bg1: "#140008",
    bg2: "#1a000e",
    b: "Someone's worst moment was witnessed by the people in the room and talked about for a week. Shame had geography. It stayed local and eventually faded.",
    a: "A bad moment becomes a reel, a meme, and a trending topic by evening. Millions watch, share, and move on before dinner. Public humiliation became the most scalable form of entertainment.",
    tags: ["#culture", "#serious", "#media", "#urgent"],
  },
  {
    id: "relationships",
    type: "relationships",
    ac: "#FB7185",
    bg1: "#140006",
    bg2: "#1a000c",
    b: "When you were with someone, you were with them. Conversation had your full attention. Silence was comfortable. Sitting together meant actually being together.",
    a: "Two people sit across from each other typing to other people elsewhere. Presence is physical but attention is somewhere else entirely. This became so ordinary it stopped being noticed.",
    tags: ["#relationships", "#melancholy", "#social", "#silent"],
  },
  {
    id: "mentalhealth",
    type: "mental health",
    ac: "#A78BFA",
    bg1: "#0d0a18",
    bg2: "#130f20",
    b: "If you struggled, community showed up. Neighbors, family, religious spaces - imperfect but present. Human support was not a subscription service with cancellation policies.",
    a: "There is an app for anxiety, a subscription for meditation, a chatbot for grief, a paid tier for belonging. Basic human support was productized and put behind a paywall.",
    tags: ["#mentalhealth", "#dystopian", "#ironic", "#inequality"],
  },
  {
    id: "education",
    type: "education",
    ac: "#FBBF24",
    bg1: "#110d00",
    bg2: "#181200",
    b: "Education was an investment a society made in its people. The idea of a young person starting adult life with a six-figure debt for a degree was considered a policy failure.",
    a: "You take a loan to get a degree to get a job to repay the loan. The credential costs more than it returns for most. This was repackaged as investing in yourself.",
    tags: ["#education", "#economic", "#inequality", "#urgent"],
  },
  {
    id: "environment",
    type: "environment",
    ac: "#4ADE80",
    bg1: "#021008",
    bg2: "#041810",
    b: "Growth meant more people had what they needed. A company expanding was understood as providing value, not simply extracting until the resource was gone.",
    a: "Quarterly targets require burning through materials at a pace the planet cannot absorb. The projections show the math does not work. The targets stay the same anyway.",
    tags: ["#environment", "#dystopian", "#urgent", "#serious"],
  },
  {
    id: "media",
    type: "media",
    ac: "#FF6B35",
    bg1: "#110600",
    bg2: "#180c00",
    b: "You read or watched what you chose. Attention was yours to direct. The newspaper did not monitor your face to find which headline made you angrier and serve you more of it.",
    a: "Entire industries are built to intercept your focus before you decide where to point it. Algorithms study what keeps you scrolling and optimize for it at a biological level.",
    tags: ["#media", "#tech", "#dystopian", "#urgent"],
  },
  {
    id: "labor",
    type: "labor",
    ac: "#06B6D4",
    bg1: "#021018",
    bg2: "#041820",
    b: "A job came with structure - a set wage, predictable hours, some protection if things went wrong. The arrangement wasn't always fair but both sides understood the terms.",
    a: "Flexible work means you absorb all the risk. No floor, no safety net, no sick leave, no tenure. The instability was relabeled as freedom and sold as a lifestyle upgrade.",
    tags: ["#labor", "#economic", "#inequality", "#darkhumor"],
  },
  {
    id: "housing",
    type: "housing",
    ac: "#D4A017",
    bg1: "#100c00",
    bg2: "#181200",
    b: "Renting was a starting point. You saved, then you bought, then you had something to pass on. Ownership was within reach for people with ordinary jobs and ordinary patience.",
    a: "Home prices outpaced salaries for two decades. Renting indefinitely is now called lifestyle flexibility. Landlords own ten homes. Many people own zero and call it a choice.",
    tags: ["#housing", "#economic", "#inequality", "#serious"],
  },
  {
    id: "community",
    type: "community",
    ac: "#8B5CF6",
    bg1: "#0d0818",
    bg2: "#120d22",
    b: "A neighbor helped because you were nearby. Community wasn't optional or metered. The infrastructure of belonging was built into the geography of where people lived.",
    a: "There is an app for accountability partners, a paid platform for community, a subscription for shared purpose. What used to be free and local is now a SaaS product with a monthly tier.",
    tags: ["#community", "#social", "#ironic", "#dystopian"],
  },
  {
    id: "parenting",
    type: "parenting",
    ac: "#60A5FA",
    bg1: "#040e18",
    bg2: "#081620",
    b: "Children were bored and boredom made them creative. They played outside, invented games, and occupied themselves with whatever was around. Attention was earned slowly.",
    a: "An algorithm decides what a three-year-old watches next before the child finishes processing the last video. Screens became default childcare. Dopamine got optimized before language did.",
    tags: ["#parenting", "#tech", "#serious", "#urgent"],
  },
  {
    id: "healthcare",
    type: "healthcare",
    ac: "#EF4444",
    bg1: "#140004",
    bg2: "#1c0008",
    b: "Getting sick was not also a financial catastrophe. The idea that seeing a doctor depended on whether your employer chose the right plan would have sounded like dystopian fiction.",
    a: "People stay in jobs they hate because leaving means losing health coverage. Medical debt is the leading cause of personal bankruptcy. Survival became an employment benefit.",
    tags: ["#healthcare", "#inequality", "#urgent", "#serious"],
  },
  {
    id: "ambition",
    type: "ambition",
    ac: "#F59E0B",
    bg1: "#110800",
    bg2: "#1a1000",
    b: "Extreme wealth was understood to involve luck, inheritance, and the labor of many people compensated far less. The ultra-rich were not automatically considered role models.",
    a: "Billionaires have personal fan bases who defend them online. Their productivity habits are studied. Their opinions on policy are treated as expertise. Wealth became the primary marker of intelligence.",
    tags: ["#ambition", "#culture", "#ironic", "#darkhumor"],
  },
  {
    id: "time",
    type: "time",
    ac: "#94A3B8",
    bg1: "#0c0e12",
    bg2: "#111318",
    b: "Leisure was the point. Rest was the reward. A person who was always occupied was a person who hadn't yet arrived somewhere worth being. Free time was what you worked toward.",
    a: "Being busy is the personality now. Saying you have no time is how you signal importance. Rest requires an apology. Calendar density became a publicly acceptable measure of human worth.",
    tags: ["#time", "#corporate", "#burnout", "#darkhumor"],
  },
  {
    id: "identity",
    type: "identity",
    ac: "#EC4899",
    bg1: "#140010",
    bg2: "#1c0018",
    b: "You were a person. You had a job, some friends, some opinions. Packaging yourself as a brand and maintaining a curated public persona was reserved for celebrities and politicians.",
    a: "Everyone is now a brand with metrics. Follower count signals social worth. Authenticity is a content strategy. Being yourself online requires a posting schedule and a niche.",
    tags: ["#identity", "#social", "#ironic", "#media"],
  },
  {
    id: "democracy",
    type: "democracy",
    ac: "#F97316",
    bg1: "#120600",
    bg2: "#1a0c00",
    b: "Civic participation meant showing up - to vote, to local meetings, to protests, to conversations that were slow and sometimes boring. Change required presence and patience.",
    a: "Sharing an outrage post is called advocacy. Liking something is called raising awareness. Participation was replaced by reaction, and reaction was monetized by platforms that benefit from anger.",
    tags: ["#democracy", "#media", "#ironic", "#serious"],
  },
  {
    id: "creativity",
    type: "creativity",
    ac: "#34D399",
    bg1: "#021010",
    bg2: "#041818",
    b: "You made things because the making mattered. A painting didn't need views. A song didn't need streams. The work was complete when it was finished, not when it performed.",
    a: "Creating without publishing is considered a waste of potential reach. Every piece needs a hook and a call to action. Art was quietly reclassified as content, and content is only valuable if it converts.",
    tags: ["#creativity", "#media", "#culture", "#melancholy"],
  },
];
