import type {
  BrandSpotlight,
  DigitalAwareness,
  ProductAlternative,
  ShopCategory,
} from "./types";

export const SHOP_CATEGORIES: ShopCategory[] = [
  { id: "bathroom", label: "Bathroom", hint: "Toothpaste, soap, shampoo", emoji: "🪥" },
  { id: "kitchen", label: "Kitchen", hint: "Noodles, coffee, cleaning", emoji: "🍳" },
  { id: "snacks", label: "Snacks & pantry", hint: "Chips, biscuits, staples", emoji: "🥨" },
  { id: "personal", label: "Personal care", hint: "Razors, moisturisers", emoji: "🧴" },
  { id: "home", label: "Home care", hint: "Detergent, dishwash", emoji: "🧺" },
  { id: "wear", label: "Clothing & footwear", hint: "Everyday wear, not luxury", emoji: "👟" },
  { id: "tech", label: "Everyday tech", hint: "Earbuds, mid-range phones", emoji: "🎧" },
];

export const PRODUCT_ALTERNATIVES: ProductAlternative[] = [
  {
    id: "colgate-perfora",
    categoryId: "bathroom",
    occasion: "Daily toothpaste",
    common: {
      brand: "Colgate",
      product: "MaxFresh / Strong Teeth (≈150g tube)",
      ownership: "mnc-global",
      ownershipNote: "Colgate-Palmolive — US-listed MNC; manufactures widely in India.",
    },
    alternative: {
      brand: "Perfora",
      product: "Dream White / Fresh Anti-Cavity (≈100–150g)",
      ownership: "indian-founded",
      ownershipNote: "Founded in India; D2C oral care brand (Perfora Life).",
      website: "https://www.perforacare.com",
    },
    match: "strong",
    whyMatch:
      "Both are fluoride toothpastes for everyday brushing — same aisle, same habit, similar tube sizes.",
    price: {
      basis: "≈100g toothpaste tube, MRP",
      commonRange: [90, 130],
      altRange: [120, 180],
      note: "Perfora is often pricier per gram; watch for bundle offers.",
    },
  },
  {
    id: "dove-medimix",
    categoryId: "bathroom",
    occasion: "Bathing soap",
    common: {
      brand: "Dove",
      product: "Beauty Cream Bar (≈125g × 3 pack)",
      ownership: "mnc-global",
      ownershipNote: "Unilever — Anglo-Dutch MNC; Dove made in India.",
    },
    alternative: {
      brand: "Medimix",
      product: "Classic Ayurvedic soap (≈125g bar)",
      ownership: "indian-founded",
      ownershipNote: "Cholayil — Indian family-owned (Kerala).",
      website: "https://www.medimixayurveda.com",
    },
    match: "good",
    whyMatch:
      "Both are daily bath soaps. Medimix is ayurvedic/herbal rather than moisturising — same job, different feel.",
    notSameAs: "Not a moisturising 1:1 — pick Medimix if you prefer herbal bars.",
    price: {
      basis: "Single ≈125g bar, MRP",
      commonRange: [80, 110],
      altRange: [45, 70],
      note: "Medimix is usually cheaper per bar.",
    },
  },
  {
    id: "hns-bare-anatomy",
    categoryId: "bathroom",
    occasion: "Anti-dandruff shampoo",
    common: {
      brand: "Head & Shoulders",
      product: "Cool Menthol (≈340ml)",
      ownership: "mnc-global",
      ownershipNote: "P&G — US MNC.",
    },
    alternative: {
      brand: "Bare Anatomy",
      product: "Anti-Dandruff shampoo (≈250ml)",
      ownership: "indian-founded",
      ownershipNote: "Indian D2C brand (Varesce Life Sciences).",
      website: "https://www.bareanatomy.in",
    },
    match: "good",
    whyMatch: "Both target dandruff/scalp care at similar urban price points.",
    price: {
      basis: "≈250ml bottle, MRP",
      commonRange: [320, 420],
      altRange: [350, 500],
      note: "Bare Anatomy runs frequent online discounts.",
    },
  },
  {
    id: "maggi-yippee",
    categoryId: "kitchen",
    occasion: "Instant noodles (2-min)",
    common: {
      brand: "Maggi",
      product: "Masala noodles (≈70g pack)",
      ownership: "mnc-global",
      ownershipNote: "Nestlé — Swiss MNC.",
    },
    alternative: {
      brand: "Sunfeast Yippee",
      product: "Mood Masala (≈65g pack)",
      ownership: "indian-listed",
      ownershipNote: "ITC — Indian listed company (Kolkata HQ).",
      website: "https://www.itcportal.com",
    },
    match: "strong",
    whyMatch: "Same cook time, pack size, and masala noodle occasion — closest like-for-like swap.",
    price: {
      basis: "Single pack, MRP",
      commonRange: [12, 16],
      altRange: [12, 16],
      note: "Often identical MRP.",
    },
  },
  {
    id: "nescafe-continental",
    categoryId: "kitchen",
    occasion: "Instant coffee at home",
    common: {
      brand: "Nescafé",
      product: "Classic / Sunrise (≈50g jar)",
      ownership: "mnc-global",
      ownershipNote: "Nestlé — Swiss MNC.",
    },
    alternative: {
      brand: "Continental",
      product: "Speciale / Strong (≈50g)",
      ownership: "indian-listed",
      ownershipNote: "CCL Products — Indian listed (Hyderabad).",
      website: "https://www.continental.coffee",
    },
    match: "strong",
    whyMatch: "Both are instant coffee jars for home brewing — same size band.",
    price: {
      basis: "≈50g jar, MRP",
      commonRange: [160, 210],
      altRange: [140, 190],
      note: "Continental is often slightly cheaper.",
    },
  },
  {
    id: "lays-haldiram",
    categoryId: "snacks",
    occasion: "Potato chips craving",
    common: {
      brand: "Lay's",
      product: "Classic Salted (≈52g)",
      ownership: "mnc-global",
      ownershipNote: "PepsiCo — US MNC.",
    },
    alternative: {
      brand: "Haldiram's",
      product: "Classic Salted Chips (≈50–55g)",
      ownership: "indian-founded",
      ownershipNote: "Haldiram's — Indian family-owned (Nagpur).",
      website: "https://www.haldirams.com",
    },
    match: "good",
    whyMatch: "Same thin potato chip format for tea-time.",
    price: {
      basis: "≈50g chip pack, MRP",
      commonRange: [18, 25],
      altRange: [18, 25],
      note: "Very similar street price.",
    },
  },
  {
    id: "oreo-parle",
    categoryId: "snacks",
    occasion: "Tea-time biscuit",
    common: {
      brand: "Oreo",
      product: "Original (≈120g pack)",
      ownership: "mnc-global",
      ownershipNote: "Mondelez — US MNC.",
    },
    alternative: {
      brand: "Parle-G",
      product: "Glucose biscuit (≈100–150g)",
      ownership: "indian-founded",
      ownershipNote: "Parle Products — Indian family-owned.",
    },
    match: "situational",
    whyMatch: "Same tea-dipping biscuit moment — not a cream sandwich clone.",
    notSameAs: "For chocolate cream, try Sunfeast Dark Fantasy (ITC, Indian listed).",
    price: {
      basis: "≈100g pack, MRP",
      commonRange: [30, 50],
      altRange: [10, 30],
      note: "Parle-G is far cheaper.",
    },
  },
  {
    id: "gillette-bombay",
    categoryId: "personal",
    occasion: "Cartridge razor refills",
    common: {
      brand: "Gillette",
      product: "Fusion / Mach3 cartridges (2-pack)",
      ownership: "mnc-global",
      ownershipNote: "P&G — US MNC.",
    },
    alternative: {
      brand: "Bombay Shaving Company",
      product: "Sensi / Premium cartridges (2-pack)",
      ownership: "indian-founded",
      ownershipNote: "Indian D2C grooming brand (Gurugram).",
      website: "https://www.bombayshavingcompany.com",
    },
    match: "strong",
    whyMatch: "Same handle-and-cartridge model for men's shaving.",
    price: {
      basis: "2 refills, MRP",
      commonRange: [400, 550],
      altRange: [250, 400],
      note: "Bombay Shaving often wins on subscription.",
    },
  },
  {
    id: "nivea-dot-key",
    categoryId: "personal",
    occasion: "Face moisturiser",
    common: {
      brand: "Nivea",
      product: "Soft Cream (≈100ml)",
      ownership: "mnc-global",
      ownershipNote: "Beiersdorf — German MNC.",
    },
    alternative: {
      brand: "Dot & Key",
      product: "Barrier repair gel-cream (≈50ml)",
      ownership: "indian-founded",
      ownershipNote: "Indian D2C skincare (Dot & Key Wellness).",
      website: "https://www.dotandkey.com",
    },
    match: "good",
    whyMatch: "Both are daily face moisturisers — Dot & Key is gel-weight for humid climates.",
    price: {
      basis: "Daily moisturiser, MRP",
      commonRange: [250, 320],
      altRange: [350, 450],
      note: "Compare price per ml on the label.",
    },
  },
  {
    id: "ariel-ghari",
    categoryId: "home",
    occasion: "Laundry detergent",
    common: {
      brand: "Ariel",
      product: "Matic top-load (≈2kg)",
      ownership: "mnc-global",
      ownershipNote: "P&G — US MNC.",
    },
    alternative: {
      brand: "Ghari",
      product: "Detergent powder (≈2kg)",
      ownership: "indian-founded",
      ownershipNote: "Rohit Surfactants — Indian family-owned (Kanpur).",
      website: "https://www.ghari.in",
    },
    match: "good",
    whyMatch: "Both are powder detergents for Indian washing.",
    notSameAs: "Surf Excel is also P&G — Ghari is the honest budget alternative.",
    price: {
      basis: "≈2kg powder, MRP",
      commonRange: [350, 450],
      altRange: [120, 180],
      note: "Ghari is significantly cheaper.",
    },
  },
  {
    id: "vim-exo",
    categoryId: "home",
    occasion: "Dishwashing",
    common: {
      brand: "Vim",
      product: "Liquid gel (≈500ml)",
      ownership: "mnc-global",
      ownershipNote: "Hindustan Unilever — Anglo-Dutch MNC.",
    },
    alternative: {
      brand: "Exo",
      product: "Dishwash bar or liquid",
      ownership: "indian-listed",
      ownershipNote: "RSPL — Indian company (Kanpur).",
    },
    match: "good",
    whyMatch: "Both cut grease from Indian cooking oils.",
    price: {
      basis: "One month family use, MRP",
      commonRange: [90, 120],
      altRange: [45, 90],
      note: "Exo bar is cheapest.",
    },
  },
  {
    id: "nike-campus",
    categoryId: "wear",
    occasion: "Daily walking shoes",
    common: {
      brand: "Nike / Adidas",
      product: "Entry running shoe",
      ownership: "mnc-global",
      ownershipNote: "US / German sportswear MNCs.",
    },
    alternative: {
      brand: "Campus",
      product: "North Plus / street running line",
      ownership: "indian-listed",
      ownershipNote: "Campus Activewear — Indian listed (Jalandhar).",
      website: "https://www.campusshoes.com",
    },
    match: "good",
    whyMatch: "Everyday commute — not pro-athlete gear.",
    notSameAs: "Not comparable to Nike Air Max or premium runners.",
    price: {
      basis: "Entry pair, MRP",
      commonRange: [3500, 5500],
      altRange: [999, 1999],
      note: "Campus is roughly half the price.",
    },
  },
  {
    id: "sony-boat",
    categoryId: "tech",
    occasion: "Commute earbuds (TWS)",
    common: {
      brand: "Sony / JBL",
      product: "Entry TWS",
      ownership: "mnc-global",
      ownershipNote: "Sony (Japan) / Harman-JBL (US).",
    },
    alternative: {
      brand: "boAt",
      product: "Airdopes series",
      ownership: "indian-listed",
      ownershipNote: "Imagine Marketing — Indian listed (Delhi NCR).",
      website: "https://www.boat-lifestyle.com",
    },
    match: "good",
    whyMatch: "Same wireless earbud use case for music and calls.",
    notSameAs: "Sony XM ANC flagships are a different tier.",
    price: {
      basis: "Entry TWS, MRP",
      commonRange: [4000, 6000],
      altRange: [999, 2499],
      note: "Check warranty in your city.",
    },
  },
  {
    id: "samsung-lava",
    categoryId: "tech",
    occasion: "Budget 5G phone",
    common: {
      brand: "Samsung Galaxy A",
      product: "A15 / A16 5G class",
      ownership: "mnc-global",
      ownershipNote: "Samsung — Korean MNC; assembled in India.",
    },
    alternative: {
      brand: "Lava",
      product: "Blaze / Agni 5G series",
      ownership: "indian-founded",
      ownershipNote: "Lava International — Indian company (Noida).",
      website: "https://www.lavamobiles.com",
    },
    match: "situational",
    whyMatch: "Same ₹10k–₹15k buyer comparing specs.",
    notSameAs: "iPhone vs Lava is not listed — different buyer entirely.",
    price: {
      basis: "Entry 5G handset, MRP",
      commonRange: [14000, 18000],
      altRange: [9000, 14000],
      note: "Prices move every quarter.",
    },
  },
];

export const DIGITAL_AWARENESS: DigitalAwareness[] = [
  {
    id: "youtube",
    name: "YouTube",
    icon: "▶",
    dailyUse: "Videos, learning, music, creators.",
    economics: "Alphabet (US) earns from ads and Premium; platform profit pools abroad.",
    nuance: "Useful and free — knowing, not deleting.",
    indianNotes: "Short-form: Josh, Moj. Educators often mirror on Kuku FM or own sites.",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: "💬",
    dailyUse: "Family groups, shops, coordination.",
    economics: "Meta (US) monetises via Business API.",
    nuance: "Replacing it family-wide is hard — awareness beats guilt.",
    indianNotes: "UPI and Indian shop catalogs already live inside chat.",
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "◎",
    dailyUse: "Reels, brands, creators.",
    economics: "Indian brand ad spend often bills through Meta's global ad system.",
    nuance: "Buy direct from Indian brands via their site + UPI when you can.",
  },
  {
    id: "google",
    name: "Google Search & Maps",
    icon: "⌕",
    dailyUse: "Directions, answers, Play Store.",
    economics: "Search and Play billing revenue accrues to Google (US).",
    indianNotes: "MapmyIndia (Mappls) for maps.",
    nuance: "Pick one use-case to try — maps are hard to swap cold turkey.",
  },
  {
    id: "ott",
    name: "Netflix & Prime Video",
    icon: "▣",
    dailyUse: "Weekend streaming.",
    economics: "Subscriptions fund global catalogs; royalties on foreign titles can leave India.",
    indianNotes: "SonyLIV, Zee5, Hoichoi — strong regional libraries.",
    nuance: "Rotate one month — not a moral scorecard.",
  },
  {
    id: "spotify",
    name: "Spotify",
    icon: "♫",
    dailyUse: "Commute playlists.",
    economics: "Royalties often flow to international rights holders.",
    indianNotes: "JioSaavn, Gaana — heavy on Bollywood and indie Indian artists.",
    nuance: "Same phone — copy one playlist to test.",
  },
  {
    id: "cards",
    name: "Visa & Mastercard",
    icon: "◈",
    dailyUse: "Cards for travel and online pay.",
    economics: "Network fees go to US card networks on many transactions.",
    indianNotes: "RuPay and UPI (NPCI) dominate local retail — you may already be more Swadeshi than you think.",
    nuance: "Cards useful abroad; UPI wins at the kirana.",
  },
  {
    id: "cloud",
    name: "AWS / Azure / GCP",
    icon: "☁",
    dailyUse: "Every app runs on someone's cloud.",
    economics: "Indian startups pay US hyperscalers — invisible import on their books.",
    indianNotes: "Yotta, E2E Networks — local DC options (matters more to founders).",
    nuance: "Helps explain why 'Indian apps' still send money abroad.",
  },
];

export const BRAND_SPOTLIGHT: BrandSpotlight[] = [
  {
    id: "amul",
    name: "Amul",
    type: "established",
    sector: "Dairy cooperative",
    whyListed: "Profits return to Gujarat milk farmers.",
    highlights: "Butter, cheese, ice cream, milk",
    hq: "Anand, Gujarat",
    website: "https://amul.com",
  },
  {
    id: "tata",
    name: "Tata Group",
    type: "established",
    sector: "Conglomerate",
    whyListed: "Indian-owned umbrella — salt, steel, software, hospitality.",
    highlights: "Tata Salt, Tanishq, TCS, Taj",
    hq: "Mumbai",
    website: "https://www.tata.com",
  },
  {
    id: "itc",
    name: "ITC",
    type: "established",
    sector: "FMCG & agri",
    whyListed: "Indian listed — Yippee, Aashirvaad, Sunfeast.",
    highlights: "Atta, biscuits, noodles, hotels",
    hq: "Kolkata",
    website: "https://www.itcportal.com",
  },
  {
    id: "haldiram",
    name: "Haldiram's",
    type: "established",
    sector: "Food",
    whyListed: "Family-owned Indian snack institution.",
    highlights: "Bhujia, namkeen, ready meals",
    hq: "Nagpur",
    website: "https://www.haldirams.com",
  },
  {
    id: "perfora",
    name: "Perfora",
    type: "startup",
    sector: "Oral care",
    whyListed: "Indian-founded D2C taking on global toothpaste aisles.",
    highlights: "Toothpaste, mouthwash, brushes",
    hq: "India",
    website: "https://www.perforacare.com",
  },
  {
    id: "slurrp",
    name: "Slurrp Farm",
    type: "startup",
    sector: "Kids food",
    whyListed: "Millet-first snacks with transparent ingredients.",
    highlights: "Cereals, dosa mixes, cookies",
    hq: "Gurugram",
    website: "https://slurrpfarm.com",
  },
  {
    id: "bombay-shaving",
    name: "Bombay Shaving Company",
    type: "startup",
    sector: "Grooming",
    whyListed: "Indian D2C that undercuts imported razor cartridges.",
    highlights: "Razors, trimmers, skincare",
    hq: "Gurugram",
    website: "https://www.bombayshavingcompany.com",
  },
  {
    id: "zerodha",
    name: "Zerodha",
    type: "established",
    sector: "Fintech",
    whyListed: "Bootstrap Indian broker for retail investing.",
    highlights: "Kite, Coin, Varsity",
    hq: "Bengaluru",
    website: "https://zerodha.com",
  },
  {
    id: "lava",
    name: "Lava",
    type: "established",
    sector: "Mobile phones",
    whyListed: "Designs phones in India — rare in an import-heavy category.",
    highlights: "Blaze, Agni 5G series",
    hq: "Noida",
    website: "https://www.lavamobiles.com",
  },
  {
    id: "sleepyowl",
    name: "Sleepy Owl",
    type: "startup",
    sector: "Coffee",
    whyListed: "Roasted and packaged in India.",
    highlights: "Cold brew, ground coffee",
    hq: "Delhi NCR",
    website: "https://sleepyowl.co",
  },
];
