import type {
  BrandSpotlight,
  DigitalAwareness,
  ImportOutflowBrand,
  ProductAlternative,
  ShopCategory,
} from "./types";

export const SHOP_CATEGORIES: ShopCategory[] = [
  { id: "bathroom", label: "Bathroom", hint: "Toothpaste, soap, shampoo", emoji: "🪥" },
  { id: "kitchen", label: "Kitchen", hint: "Noodles, coffee, cleaning", emoji: "🍳" },
  { id: "snacks", label: "Snacks & pantry", hint: "Chips, biscuits, staples", emoji: "🥨" },
  { id: "personal", label: "Personal care", hint: "Razors, moisturisers", emoji: "🧴" },
  { id: "home", label: "Home care", hint: "Detergent, dishwash", emoji: "🧺" },
  { id: "wear", label: "Clothing & footwear", hint: "Everyday wear, not luxury", emoji: "👟" },
  { id: "tech", label: "Everyday tech", hint: "Earbuds and audio — phones in import map", emoji: "🎧" },
];

export const PRODUCT_ALTERNATIVES: ProductAlternative[] = [
  {
    id: "colgate-perfora",
    categoryId: "bathroom",
    occasion: "Daily toothpaste",
    common: {
      brand: "Colgate",
      product: "MaxFresh / Strong Teeth (≈150g tube)",
      ownership: "mnc-global",
      ownershipNote: "Colgate-Palmolive — US-listed MNC; manufactures widely in India.",
    },
    alternative: {
      brand: "Perfora",
      product: "Dream White / Fresh Anti-Cavity (≈100–150g)",
      ownership: "indian-founded",
      ownershipNote: "Founded in India; D2C oral care brand (Perfora Life).",
      website: "https://www.perforacare.com",
    },
    match: "strong",
    whyMatch:
      "Both are fluoride toothpastes for everyday brushing — same aisle, same habit, similar tube sizes.",
    price: {
      basis: "≈100g toothpaste tube, MRP",
      commonRange: [90, 130],
      altRange: [120, 180],
      note: "Perfora is often pricier per gram; watch for bundle offers.",
    },
  },
  {
    id: "dove-medimix",
    categoryId: "bathroom",
    occasion: "Bathing soap",
    common: {
      brand: "Dove",
      product: "Beauty Cream Bar (≈125g × 3 pack)",
      ownership: "mnc-global",
      ownershipNote: "Unilever — Anglo-Dutch MNC; Dove made in India.",
    },
    alternative: {
      brand: "Medimix",
      product: "Classic Ayurvedic soap (≈125g bar)",
      ownership: "indian-founded",
      ownershipNote: "Cholayil — Indian family-owned (Kerala).",
      website: "https://www.medimixayurveda.com",
    },
    match: "good",
    whyMatch:
      "Both are daily bath soaps. Medimix is ayurvedic/herbal rather than moisturising — same job, different feel.",
    notSameAs: "Not a moisturising 1:1 — pick Medimix if you prefer herbal bars.",
    price: {
      basis: "Single ≈125g bar, MRP",
      commonRange: [80, 110],
      altRange: [45, 70],
      note: "Medimix is usually cheaper per bar.",
    },
  },
  {
    id: "hns-bare-anatomy",
    categoryId: "bathroom",
    occasion: "Anti-dandruff shampoo",
    common: {
      brand: "Head & Shoulders",
      product: "Cool Menthol (≈340ml)",
      ownership: "mnc-global",
      ownershipNote: "P&G — US MNC.",
    },
    alternative: {
      brand: "Bare Anatomy",
      product: "Anti-Dandruff shampoo (≈250ml)",
      ownership: "indian-founded",
      ownershipNote: "Indian D2C brand (Varesce Life Sciences).",
      website: "https://www.bareanatomy.in",
    },
    match: "good",
    whyMatch: "Both target dandruff/scalp care at similar urban price points.",
    price: {
      basis: "≈250ml bottle, MRP",
      commonRange: [320, 420],
      altRange: [350, 500],
      note: "Bare Anatomy runs frequent online discounts.",
    },
  },
  {
    id: "maggi-yippee",
    categoryId: "kitchen",
    occasion: "Instant noodles (2-min)",
    common: {
      brand: "Maggi",
      product: "Masala noodles (≈70g pack)",
      ownership: "mnc-global",
      ownershipNote: "Nestlé — Swiss MNC.",
    },
    alternative: {
      brand: "Sunfeast Yippee",
      product: "Mood Masala (≈65g pack)",
      ownership: "indian-listed",
      ownershipNote: "ITC — Indian listed company (Kolkata HQ).",
      website: "https://www.itcportal.com",
    },
    match: "strong",
    whyMatch: "Same cook time, pack size, and masala noodle occasion — closest like-for-like swap.",
    price: {
      basis: "Single pack, MRP",
      commonRange: [12, 16],
      altRange: [12, 16],
      note: "Often identical MRP.",
    },
  },
  {
    id: "nescafe-continental",
    categoryId: "kitchen",
    occasion: "Instant coffee at home",
    common: {
      brand: "Nescafé",
      product: "Classic / Sunrise (≈50g jar)",
      ownership: "mnc-global",
      ownershipNote: "Nestlé — Swiss MNC.",
    },
    alternative: {
      brand: "Continental",
      product: "Speciale / Strong (≈50g)",
      ownership: "indian-listed",
      ownershipNote: "CCL Products — Indian listed (Hyderabad).",
      website: "https://www.continental.coffee",
    },
    match: "strong",
    whyMatch: "Both are instant coffee jars for home brewing — same size band.",
    price: {
      basis: "≈50g jar, MRP",
      commonRange: [160, 210],
      altRange: [140, 190],
      note: "Continental is often slightly cheaper.",
    },
  },
  {
    id: "lays-haldiram",
    categoryId: "snacks",
    occasion: "Potato chips craving",
    common: {
      brand: "Lay's",
      product: "Classic Salted (≈52g)",
      ownership: "mnc-global",
      ownershipNote: "PepsiCo — US MNC.",
    },
    alternative: {
      brand: "Haldiram's",
      product: "Classic Salted Chips (≈50–55g)",
      ownership: "indian-founded",
      ownershipNote: "Haldiram's — Indian family-owned (Nagpur).",
      website: "https://www.haldirams.com",
    },
    match: "good",
    whyMatch: "Same thin potato chip format for tea-time.",
    price: {
      basis: "≈50g chip pack, MRP",
      commonRange: [18, 25],
      altRange: [18, 25],
      note: "Very similar street price.",
    },
  },
  {
    id: "oreo-parle",
    categoryId: "snacks",
    occasion: "Tea-time biscuit",
    common: {
      brand: "Oreo",
      product: "Original (≈120g pack)",
      ownership: "mnc-global",
      ownershipNote: "Mondelez — US MNC.",
    },
    alternative: {
      brand: "Parle-G",
      product: "Glucose biscuit (≈100–150g)",
      ownership: "indian-founded",
      ownershipNote: "Parle Products — Indian family-owned.",
    },
    match: "situational",
    whyMatch: "Same tea-dipping biscuit moment — not a cream sandwich clone.",
    notSameAs: "For chocolate cream, try Sunfeast Dark Fantasy (ITC, Indian listed).",
    price: {
      basis: "≈100g pack, MRP",
      commonRange: [30, 50],
      altRange: [10, 30],
      note: "Parle-G is far cheaper.",
    },
  },
  {
    id: "gillette-bombay",
    categoryId: "personal",
    occasion: "Cartridge razor refills",
    common: {
      brand: "Gillette",
      product: "Fusion / Mach3 cartridges (2-pack)",
      ownership: "mnc-global",
      ownershipNote: "P&G — US MNC.",
    },
    alternative: {
      brand: "Bombay Shaving Company",
      product: "Sensi / Premium cartridges (2-pack)",
      ownership: "indian-founded",
      ownershipNote: "Indian D2C grooming brand (Gurugram).",
      website: "https://www.bombayshavingcompany.com",
    },
    match: "strong",
    whyMatch: "Same handle-and-cartridge model for men's shaving.",
    price: {
      basis: "2 refills, MRP",
      commonRange: [400, 550],
      altRange: [250, 400],
      note: "Bombay Shaving often wins on subscription.",
    },
  },
  {
    id: "nivea-dot-key",
    categoryId: "personal",
    occasion: "Face moisturiser",
    common: {
      brand: "Nivea",
      product: "Soft Cream (≈100ml)",
      ownership: "mnc-global",
      ownershipNote: "Beiersdorf — German MNC.",
    },
    alternative: {
      brand: "Dot & Key",
      product: "Barrier repair gel-cream (≈50ml)",
      ownership: "indian-founded",
      ownershipNote: "Indian D2C skincare (Dot & Key Wellness).",
      website: "https://www.dotandkey.com",
    },
    match: "good",
    whyMatch: "Both are daily face moisturisers — Dot & Key is gel-weight for humid climates.",
    price: {
      basis: "Daily moisturiser, MRP",
      commonRange: [250, 320],
      altRange: [350, 450],
      note: "Compare price per ml on the label.",
    },
  },
  {
    id: "ariel-ghari",
    categoryId: "home",
    occasion: "Laundry detergent",
    common: {
      brand: "Ariel",
      product: "Matic top-load (≈2kg)",
      ownership: "mnc-global",
      ownershipNote: "P&G — US MNC.",
    },
    alternative: {
      brand: "Ghari",
      product: "Detergent powder (≈2kg)",
      ownership: "indian-founded",
      ownershipNote: "Rohit Surfactants — Indian family-owned (Kanpur).",
      website: "https://www.ghari.in",
    },
    match: "good",
    whyMatch: "Both are powder detergents for Indian washing.",
    notSameAs: "Surf Excel is also P&G — Ghari is the honest budget alternative.",
    price: {
      basis: "≈2kg powder, MRP",
      commonRange: [350, 450],
      altRange: [120, 180],
      note: "Ghari is significantly cheaper.",
    },
  },
  {
    id: "vim-exo",
    categoryId: "home",
    occasion: "Dishwashing",
    common: {
      brand: "Vim",
      product: "Liquid gel (≈500ml)",
      ownership: "mnc-global",
      ownershipNote: "Hindustan Unilever — Anglo-Dutch MNC.",
    },
    alternative: {
      brand: "Exo",
      product: "Dishwash bar or liquid",
      ownership: "indian-listed",
      ownershipNote: "RSPL — Indian company (Kanpur).",
    },
    match: "good",
    whyMatch: "Both cut grease from Indian cooking oils.",
    price: {
      basis: "One month family use, MRP",
      commonRange: [90, 120],
      altRange: [45, 90],
      note: "Exo bar is cheapest.",
    },
  },
  {
    id: "nike-campus",
    categoryId: "wear",
    occasion: "Daily walking shoes",
    common: {
      brand: "Nike / Adidas",
      product: "Entry running shoe",
      ownership: "mnc-global",
      ownershipNote: "US / German sportswear MNCs.",
    },
    alternative: {
      brand: "Campus",
      product: "North Plus / street running line",
      ownership: "indian-listed",
      ownershipNote: "Campus Activewear — Indian listed (Jalandhar).",
      website: "https://www.campusshoes.com",
    },
    match: "good",
    whyMatch: "Everyday commute — not pro-athlete gear.",
    notSameAs: "Not comparable to Nike Air Max or premium runners.",
    price: {
      basis: "Entry pair, MRP",
      commonRange: [3500, 5500],
      altRange: [999, 1999],
      note: "Campus is roughly half the price.",
    },
  },
  {
    id: "sony-boat",
    categoryId: "tech",
    occasion: "Commute earbuds (TWS)",
    common: {
      brand: "Sony / JBL",
      product: "Entry TWS",
      ownership: "mnc-global",
      ownershipNote: "Sony (Japan) / Harman-JBL (US).",
    },
    alternative: {
      brand: "boAt",
      product: "Airdopes series",
      ownership: "indian-listed",
      ownershipNote: "Imagine Marketing — Indian listed (Delhi NCR).",
      website: "https://www.boat-lifestyle.com",
    },
    match: "good",
    whyMatch: "Same wireless earbud use case for music and calls.",
    notSameAs: "Sony XM ANC flagships are a different tier.",
    price: {
      basis: "Entry TWS, MRP",
      commonRange: [4000, 6000],
      altRange: [999, 2499],
      note: "Check warranty in your city.",
    },
  },
];

export const DIGITAL_AWARENESS: DigitalAwareness[] = [
  {
    id: "youtube",
    name: "YouTube",
    icon: "▶",
    dailyUse: "Videos, learning, music, creators.",
    economics: "Alphabet (US) earns from ads and Premium; platform profit pools abroad.",
    nuance: "Useful and free — knowing, not deleting.",
    indianNotes: "Short-form: Josh, Moj. Educators often mirror on Kuku FM or own sites.",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: "💬",
    dailyUse: "Family groups, shops, coordination.",
    economics: "Meta (US) monetises via Business API.",
    nuance: "Replacing it family-wide is hard — awareness beats guilt.",
    indianNotes: "UPI and Indian shop catalogs already live inside chat.",
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "◎",
    dailyUse: "Reels, brands, creators.",
    economics: "Indian brand ad spend often bills through Meta's global ad system.",
    nuance: "Buy direct from Indian brands via their site + UPI when you can.",
  },
  {
    id: "google",
    name: "Google Search & Maps",
    icon: "⌕",
    dailyUse: "Directions, answers, Play Store.",
    economics: "Search and Play billing revenue accrues to Google (US).",
    indianNotes: "MapmyIndia (Mappls) for maps.",
    nuance: "Pick one use-case to try — maps are hard to swap cold turkey.",
  },
  {
    id: "ott",
    name: "Netflix & Prime Video",
    icon: "▣",
    dailyUse: "Weekend streaming.",
    economics: "Subscriptions fund global catalogs; royalties on foreign titles can leave India.",
    indianNotes: "SonyLIV, Zee5, Hoichoi — strong regional libraries.",
    nuance: "Rotate one month — not a moral scorecard.",
  },
  {
    id: "spotify",
    name: "Spotify",
    icon: "♫",
    dailyUse: "Commute playlists.",
    economics: "Royalties often flow to international rights holders.",
    indianNotes: "JioSaavn, Gaana — heavy on Bollywood and indie Indian artists.",
    nuance: "Same phone — copy one playlist to test.",
  },
  {
    id: "cards",
    name: "Visa & Mastercard",
    icon: "◈",
    dailyUse: "Cards for travel and online pay.",
    economics: "Network fees go to US card networks on many transactions.",
    indianNotes: "RuPay and UPI (NPCI) dominate local retail — you may already be more Swadeshi than you think.",
    nuance: "Cards useful abroad; UPI wins at the kirana.",
  },
  {
    id: "cloud",
    name: "AWS / Azure / GCP",
    icon: "☁",
    dailyUse: "Every app runs on someone's cloud.",
    economics: "Indian startups pay US hyperscalers — invisible import on their books.",
    indianNotes: "Yotta, E2E Networks — local DC options (matters more to founders).",
    nuance: "Helps explain why 'Indian apps' still send money abroad.",
  },
];

export const BRAND_SPOTLIGHT: BrandSpotlight[] = [
  {
    id: "amul",
    name: "Amul",
    type: "established",
    sector: "Dairy cooperative",
    whyListed: "Profits return to Gujarat milk farmers.",
    highlights: "Butter, cheese, ice cream, milk",
    hq: "Anand, Gujarat",
    website: "https://amul.com",
  },
  {
    id: "tata",
    name: "Tata Group",
    type: "established",
    sector: "Conglomerate",
    whyListed: "Indian-owned umbrella — salt, steel, software, hospitality.",
    highlights: "Tata Salt, Tanishq, TCS, Taj",
    hq: "Mumbai",
    website: "https://www.tata.com",
  },
  {
    id: "itc",
    name: "ITC",
    type: "established",
    sector: "FMCG & agri",
    whyListed: "Indian listed — Yippee, Aashirvaad, Sunfeast.",
    highlights: "Atta, biscuits, noodles, hotels",
    hq: "Kolkata",
    website: "https://www.itcportal.com",
  },
  {
    id: "haldiram",
    name: "Haldiram's",
    type: "established",
    sector: "Food",
    whyListed: "Family-owned Indian snack institution.",
    highlights: "Bhujia, namkeen, ready meals",
    hq: "Nagpur",
    website: "https://www.haldirams.com",
  },
  {
    id: "perfora",
    name: "Perfora",
    type: "startup",
    sector: "Oral care",
    whyListed: "Indian-founded D2C taking on global toothpaste aisles.",
    highlights: "Toothpaste, mouthwash, brushes",
    hq: "India",
    website: "https://www.perforacare.com",
  },
  {
    id: "slurrp",
    name: "Slurrp Farm",
    type: "startup",
    sector: "Kids food",
    whyListed: "Millet-first snacks with transparent ingredients.",
    highlights: "Cereals, dosa mixes, cookies",
    hq: "Gurugram",
    website: "https://slurrpfarm.com",
  },
  {
    id: "bombay-shaving",
    name: "Bombay Shaving Company",
    type: "startup",
    sector: "Grooming",
    whyListed: "Indian D2C that undercuts imported razor cartridges.",
    highlights: "Razors, trimmers, skincare",
    hq: "Gurugram",
    website: "https://www.bombayshavingcompany.com",
  },
  {
    id: "zerodha",
    name: "Zerodha",
    type: "established",
    sector: "Fintech",
    whyListed: "Bootstrap Indian broker for retail investing.",
    highlights: "Kite, Coin, Varsity",
    hq: "Bengaluru",
    website: "https://zerodha.com",
  },
  {
    id: "lava",
    name: "Lava",
    type: "established",
    sector: "Mobile phones",
    whyListed: "Designs phones in India — rare in an import-heavy category.",
    highlights: "Blaze, Agni 5G series",
    hq: "Noida",
    website: "https://www.lavamobiles.com",
  },
  {
    id: "sleepyowl",
    name: "Sleepy Owl",
    type: "startup",
    sector: "Coffee",
    whyListed: "Roasted and packaged in India.",
    highlights: "Cold brew, ground coffee",
    hq: "Delhi NCR",
    website: "https://sleepyowl.co",
  },
];


export const IMPORT_OUTFLOW_BRANDS: ImportOutflowBrand[] = [
  {
    id: "smartphones-premium",
    category: "Premium smartphones",
    outflowType: "electronics",
    commonSpendUse: "₹40k+ phone purchases",
    importDependency: "very-high",
    brandExamples: ["Apple iPhone", "Samsung Galaxy S/Ultra"],
    whyMoneyGoesOut: "Core IP, premium margins, and many high-value components are owned offshore even when assembly is in India.",
    indiaOptions: "No full Indian flagship equivalent yet. For value tiers, compare same-tier Indian options only.",
    honestyNote: "India has manufacturing scale-up, but premium device IP still sits mostly abroad.",
  },
  {
    id: "smartphones-budget",
    category: "Budget & mid-range smartphones",
    outflowType: "electronics",
    commonSpendUse: "Under ₹25k phone upgrades",
    importDependency: "high",
    brandExamples: ["Samsung Galaxy A", "Redmi / POCO", "Realme", "Motorola"],
    whyMoneyGoesOut: "Even India-assembled phones rely on imported chipsets, displays, and OS ecosystems tied to foreign firms.",
    indiaOptions: "Lava, Micromax, and ITEL exist but quality and software support vary widely by model — we do not list unfair phone swaps in Shop.",
    honestyNote: "Same price band does not mean same quality. Check reviews for your exact model before switching.",
  },
  {
    id: "laptops-ultrabooks",
    category: "Laptops and ultrabooks",
    outflowType: "electronics",
    commonSpendUse: "Work laptops and student machines",
    importDependency: "very-high",
    brandExamples: ["Apple MacBook", "Dell XPS", "HP Spectre", "Lenovo ThinkPad"],
    whyMoneyGoesOut: "Processor ecosystem, OS licensing, and premium brand economics are mostly controlled by foreign firms.",
    indiaOptions: "Indian-assembled options exist in lower tiers; enterprise-grade Indian laptop brands are still limited.",
    honestyNote: "Strong outflow lane for high-value consumer tech.",
  },
  {
    id: "gaming-consoles",
    category: "Gaming consoles",
    outflowType: "electronics",
    commonSpendUse: "Console purchases plus subscriptions",
    importDependency: "very-high",
    brandExamples: ["Sony PlayStation", "Microsoft Xbox", "Nintendo Switch"],
    whyMoneyGoesOut: "Hardware, first-party games, and subscription ecosystems are foreign-owned.",
    indiaOptions: "PC gaming and Indian studios exist, but no Indian console ecosystem at scale.",
    honestyNote: "High import and software royalty outflow with low domestic substitution today.",
  },
  {
    id: "crude-oil-fuels",
    category: "Petrol, diesel, and LPG chain",
    outflowType: "energy",
    commonSpendUse: "Daily transport and household gas",
    importDependency: "very-high",
    brandExamples: ["Global crude suppliers"],
    whyMoneyGoesOut: "India imports most crude requirements, so fuel demand directly drives forex outflow.",
    indiaOptions: "EV transition, public transport, and fuel efficiency reduce outflow intensity.",
    honestyNote: "Structurally one of the largest import outflow buckets.",
  },
  {
    id: "global-saas",
    category: "Global SaaS subscriptions",
    outflowType: "digital-services",
    commonSpendUse: "Design, productivity, AI, and cloud tools",
    importDependency: "high",
    brandExamples: ["Adobe", "Canva", "OpenAI", "Atlassian"],
    whyMoneyGoesOut: "Recurring subscription billing and enterprise licenses are paid to offshore headquarters.",
    indiaOptions: "Zoho and Indian SaaS alternatives can replace some workflows fully.",
    honestyNote: "Best immediate switching category where quality is comparable for your use case.",
  },
  {
    id: "app-store-fees",
    category: "App ecosystem fees",
    outflowType: "digital-services",
    commonSpendUse: "In-app purchases and premium mobile apps",
    importDependency: "high",
    brandExamples: ["Apple App Store", "Google Play billing"],
    whyMoneyGoesOut: "Platform fees and commissions are tied to foreign app-store rails.",
    indiaOptions: "UPI web-checkout and direct subscriptions where available.",
    honestyNote: "Even Indian apps can leak value if billed via foreign platform rails.",
  },
  {
    id: "premium-sportswear",
    category: "Premium sportswear",
    outflowType: "consumer-goods",
    commonSpendUse: "Lifestyle and performance shoes",
    importDependency: "medium",
    brandExamples: ["Nike", "Adidas", "Puma"],
    whyMoneyGoesOut: "Brand premium, licensing, and design ownership sit with global parent companies.",
    indiaOptions: "Campus, Red Tape, HRX, Performax are improving in mass and mid tiers.",
    honestyNote: "High-end performance categories still stronger with global players.",
  },
  {
    id: "premium-audio",
    category: "Premium audio",
    outflowType: "electronics",
    commonSpendUse: "ANC headphones and premium earbuds",
    importDependency: "high",
    brandExamples: ["Sony", "Bose", "Sennheiser", "Apple AirPods"],
    whyMoneyGoesOut: "Acoustic IP, chip integration, and premium brand value are foreign-owned.",
    indiaOptions: "boAt and Noise are strong in budget-to-mid tiers but not top-tier ANC leaders yet.",
    honestyNote: "Budget commute audio is easier to localize than audiophile tiers.",
  },
  {
    id: "fmcg-personal-care",
    category: "Imported personal care & beauty",
    outflowType: "consumer-goods",
    commonSpendUse: "Shampoo, skincare, deodorant",
    importDependency: "medium",
    brandExamples: ["L'Oreal", "Unilever (Dove)", "P&G (Head & Shoulders)", "Nivea"],
    whyMoneyGoesOut: "Global FMCG parents earn royalties and margins on formulations even when products are made in India.",
    indiaOptions: "Himalaya, Mamaearth, Biotique, Patanjali, and many D2C Indian brands cover daily care well.",
    honestyNote: "Check ownership - some Indian labels are licensed by MNCs.",
  },
  {
    id: "packaged-foods-snacks",
    category: "Imported snacks & beverages",
    outflowType: "consumer-goods",
    commonSpendUse: "Chips, chocolates, soft drinks",
    importDependency: "medium",
    brandExamples: ["Coca-Cola", "PepsiCo", "Mondelez (Cadbury)", "Nestle (Maggi/Kits)"],
    whyMoneyGoesOut: "Brand IP, marketing spend, and profit repatriation flow to global HQs.",
    indiaOptions: "Haldiram's, Bikaji, Paper Boat, Amul, and regional brands keep more value local.",
    honestyNote: "Many items are manufactured here; the outflow is often profit and IP, not the physical good.",
  },
  {
    id: "pharma-devices",
    category: "Medical devices & implants",
    outflowType: "electronics",
    commonSpendUse: "Stents, implants, diagnostic machines",
    importDependency: "very-high",
    brandExamples: ["Medtronic", "Abbott", "Siemens Healthineers", "GE HealthCare"],
    whyMoneyGoesOut: "High-tech devices and implants are heavily import-dependent with long R&D cycles abroad.",
    indiaOptions: "Make in India push is growing; many hospitals still rely on imported devices for critical care.",
    honestyNote: "Health outcomes matter more than origin - but it is a major forex lane.",
  },
  {
    id: "gold-jewellery",
    category: "Gold jewellery demand",
    outflowType: "luxury",
    commonSpendUse: "Weddings and festival gold buying",
    importDependency: "very-high",
    brandExamples: ["Imported bullion supply chain"],
    whyMoneyGoesOut: "India is among the largest gold importers; a large share of jewellery demand is met via imported metal.",
    indiaOptions: "Hallmarked Indian jewellers use the same global price; reducing discretionary gold import is the lever.",
    honestyNote: "Cultural demand makes this one of the hardest categories to swap locally.",
  },
  {
    id: "luxury-watches",
    category: "Luxury watches",
    outflowType: "luxury",
    commonSpendUse: "Premium gifting and status purchases",
    importDependency: "high",
    brandExamples: ["Rolex", "Omega", "TAG Heuer", "Casio (premium lines)"],
    whyMoneyGoesOut: "Swiss and Japanese watchmakers capture design IP and retail margins offshore.",
    indiaOptions: "Titan, Fastrack, and Indian microbrands cover mid tiers; ultra-luxury remains import-led.",
    honestyNote: "Discretionary category with near-total foreign brand dominance at the top.",
  },
  {
    id: "streaming-video",
    category: "Global streaming subscriptions",
    outflowType: "digital-services",
    commonSpendUse: "Netflix, Prime Video, Disney+ Hotstar premium",
    importDependency: "high",
    brandExamples: ["Netflix", "Amazon Prime Video", "Apple TV+"],
    whyMoneyGoesOut: "Content licensing fees and platform economics are paid to foreign rights holders.",
    indiaOptions: "JioCinema, Zee5, SonyLIV host strong Indian catalogues; mix based on what you watch.",
    honestyNote: "Hotstar is Indian-operated but still licenses a lot of global content.",
  },
  {
    id: "ev-batteries",
    category: "EV batteries & cells",
    outflowType: "electronics",
    commonSpendUse: "Electric cars and two-wheelers",
    importDependency: "very-high",
    brandExamples: ["CATL", "LG Energy", "Panasonic", "Samsung SDI"],
    whyMoneyGoesOut: "Cell chemistry and pack IP are concentrated in East Asia and the West.",
    indiaOptions: "Ola, Ather, Tata EVs assemble locally but still import cells; PLI is building capacity.",
    honestyNote: "Buying Indian EV brands helps jobs and assembly; cells may still be imported for years.",
  },
];
