import type { BrandSpotlight, DigitalAwareness, ImportOutflowBrand } from "./types";

export const DIGITAL_AWARENESS: DigitalAwareness[] = [
  {
    id: "youtube",
    name: "YouTube",
    icon: "▶",
    dailyUse: "Videos, learning, music, creators.",
    economics: "Alphabet (US) earns from ads and Premium; platform profit pools abroad.",
    nuance: "Useful and free — knowing, not deleting.",
    indianNotes: "Short-form: Josh, Moj. Educators often mirror on Kuku FM or own sites.",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: "💬",
    dailyUse: "Family groups, shops, coordination.",
    economics: "Meta (US) monetises via Business API.",
    nuance: "Replacing it family-wide is hard — awareness beats guilt.",
    indianNotes: "UPI and Indian shop catalogs already live inside chat.",
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "◎",
    dailyUse: "Reels, brands, creators.",
    economics: "Indian brand ad spend often bills through Meta's global ad system.",
    nuance: "Buy direct from Indian brands via their site + UPI when you can.",
  },
  {
    id: "google",
    name: "Google Search & Maps",
    icon: "⌕",
    dailyUse: "Directions, answers, Play Store.",
    economics: "Search and Play billing revenue accrues to Google (US).",
    indianNotes: "MapmyIndia (Mappls) for maps.",
    nuance: "Pick one use-case to try — maps are hard to swap cold turkey.",
  },
  {
    id: "ott",
    name: "Netflix & Prime Video",
    icon: "▣",
    dailyUse: "Weekend streaming.",
    economics: "Subscriptions fund global catalogs; royalties on foreign titles can leave India.",
    indianNotes: "SonyLIV, Zee5, Hoichoi — strong regional libraries.",
    nuance: "Rotate one month — not a moral scorecard.",
  },
  {
    id: "spotify",
    name: "Spotify",
    icon: "♫",
    dailyUse: "Commute playlists.",
    economics: "Royalties often flow to international rights holders.",
    indianNotes: "JioSaavn, Gaana — heavy on Bollywood and indie Indian artists.",
    nuance: "Same phone — copy one playlist to test.",
  },
  {
    id: "cards",
    name: "Visa & Mastercard",
    icon: "◈",
    dailyUse: "Cards for travel and online pay.",
    economics: "Network fees go to US card networks on many transactions.",
    indianNotes: "RuPay and UPI (NPCI) dominate local retail — you may already be more Swadeshi than you think.",
    nuance: "Cards useful abroad; UPI wins at the kirana.",
  },
  {
    id: "cloud",
    name: "AWS / Azure / GCP",
    icon: "☁",
    dailyUse: "Every app runs on someone's cloud.",
    economics: "Indian startups pay US hyperscalers — invisible import on their books.",
    indianNotes: "Yotta, E2E Networks — local DC options (matters more to founders).",
    nuance: "Helps explain why 'Indian apps' still send money abroad.",
  },
];

export const BRAND_SPOTLIGHT: BrandSpotlight[] = [
  {
    id: "amul",
    name: "Amul",
    type: "established",
    sector: "Dairy cooperative",
    whyListed: "Profits return to Gujarat milk farmers.",
    highlights: "Butter, cheese, ice cream, milk",
    hq: "Anand, Gujarat",
    website: "https://amul.com",
  },
  {
    id: "tata",
    name: "Tata Group",
    type: "established",
    sector: "Conglomerate",
    whyListed: "Indian-owned umbrella — salt, steel, software, hospitality.",
    highlights: "Tata Salt, Tanishq, TCS, Taj",
    hq: "Mumbai",
    website: "https://www.tata.com",
  },
  {
    id: "itc",
    name: "ITC",
    type: "established",
    sector: "FMCG & agri",
    whyListed: "Indian listed — Yippee, Aashirvaad, Sunfeast.",
    highlights: "Atta, biscuits, noodles, hotels",
    hq: "Kolkata",
    website: "https://www.itcportal.com",
  },
  {
    id: "haldiram",
    name: "Haldiram's",
    type: "established",
    sector: "Food",
    whyListed: "Family-owned Indian snack institution.",
    highlights: "Bhujia, namkeen, ready meals",
    hq: "Nagpur",
    website: "https://www.haldirams.com",
  },
  {
    id: "perfora",
    name: "Perfora",
    type: "startup",
    sector: "Oral care",
    whyListed: "Indian-founded D2C taking on global toothpaste aisles.",
    highlights: "Toothpaste, mouthwash, brushes",
    hq: "India",
    website: "https://www.perforacare.com",
  },
  {
    id: "slurrp",
    name: "Slurrp Farm",
    type: "startup",
    sector: "Kids food",
    whyListed: "Millet-first snacks with transparent ingredients.",
    highlights: "Cereals, dosa mixes, cookies",
    hq: "Gurugram",
    website: "https://slurrpfarm.com",
  },
  {
    id: "bombay-shaving",
    name: "Bombay Shaving Company",
    type: "startup",
    sector: "Grooming",
    whyListed: "Indian D2C that undercuts imported razor cartridges.",
    highlights: "Razors, trimmers, skincare",
    hq: "Gurugram",
    website: "https://www.bombayshavingcompany.com",
  },
  {
    id: "zerodha",
    name: "Zerodha",
    type: "established",
    sector: "Fintech",
    whyListed: "Bootstrap Indian broker for retail investing.",
    highlights: "Kite, Coin, Varsity",
    hq: "Bengaluru",
    website: "https://zerodha.com",
  },
  {
    id: "lava",
    name: "Lava",
    type: "established",
    sector: "Mobile phones",
    whyListed: "Designs phones in India — rare in an import-heavy category.",
    highlights: "Blaze, Agni 5G series",
    hq: "Noida",
    website: "https://www.lavamobiles.com",
  },
  {
    id: "sleepyowl",
    name: "Sleepy Owl",
    type: "startup",
    sector: "Coffee",
    whyListed: "Roasted and packaged in India.",
    highlights: "Cold brew, ground coffee",
    hq: "Delhi NCR",
    website: "https://sleepyowl.co",
  },
];


export const IMPORT_OUTFLOW_BRANDS: ImportOutflowBrand[] = [
  {
    id: "smartphones-premium",
    category: "Premium smartphones",
    outflowType: "electronics",
    commonSpendUse: "₹40k+ phone purchases",
    importDependency: "very-high",
    brandExamples: ["Apple iPhone", "Samsung Galaxy S/Ultra"],
    whyMoneyGoesOut: "Core IP, premium margins, and many high-value components are owned offshore even when assembly is in India.",
    indiaOptions: "No full Indian flagship equivalent yet. For value tiers, compare same-tier Indian options only.",
    honestyNote: "India has manufacturing scale-up, but premium device IP still sits mostly abroad.",
  },
  {
    id: "smartphones-budget",
    category: "Budget & mid-range smartphones",
    outflowType: "electronics",
    commonSpendUse: "Under ₹25k phone upgrades",
    importDependency: "high",
    brandExamples: ["Samsung Galaxy A", "Redmi / POCO", "Realme", "Motorola"],
    whyMoneyGoesOut: "Even India-assembled phones rely on imported chipsets, displays, and OS ecosystems tied to foreign firms.",
    indiaOptions: "Lava, Micromax, and ITEL exist but quality and software support vary widely by model — we do not list unfair phone swaps in Shop.",
    honestyNote: "Same price band does not mean same quality. Check reviews for your exact model before switching.",
  },
  {
    id: "laptops-ultrabooks",
    category: "Laptops and ultrabooks",
    outflowType: "electronics",
    commonSpendUse: "Work laptops and student machines",
    importDependency: "very-high",
    brandExamples: ["Apple MacBook", "Dell XPS", "HP Spectre", "Lenovo ThinkPad"],
    whyMoneyGoesOut: "Processor ecosystem, OS licensing, and premium brand economics are mostly controlled by foreign firms.",
    indiaOptions: "Indian-assembled options exist in lower tiers; enterprise-grade Indian laptop brands are still limited.",
    honestyNote: "Strong outflow lane for high-value consumer tech.",
  },
  {
    id: "gaming-consoles",
    category: "Gaming consoles",
    outflowType: "electronics",
    commonSpendUse: "Console purchases plus subscriptions",
    importDependency: "very-high",
    brandExamples: ["Sony PlayStation", "Microsoft Xbox", "Nintendo Switch"],
    whyMoneyGoesOut: "Hardware, first-party games, and subscription ecosystems are foreign-owned.",
    indiaOptions: "PC gaming and Indian studios exist, but no Indian console ecosystem at scale.",
    honestyNote: "High import and software royalty outflow with low domestic substitution today.",
  },
  {
    id: "crude-oil-fuels",
    category: "Petrol, diesel, and LPG chain",
    outflowType: "energy",
    commonSpendUse: "Daily transport and household gas",
    importDependency: "very-high",
    brandExamples: ["Global crude suppliers"],
    whyMoneyGoesOut: "India imports most crude requirements, so fuel demand directly drives forex outflow.",
    indiaOptions: "EV transition, public transport, and fuel efficiency reduce outflow intensity.",
    honestyNote: "Structurally one of the largest import outflow buckets.",
  },
  {
    id: "global-saas",
    category: "Global SaaS subscriptions",
    outflowType: "digital-services",
    commonSpendUse: "Design, productivity, AI, and cloud tools",
    importDependency: "high",
    brandExamples: ["Adobe", "Canva", "OpenAI", "Atlassian"],
    whyMoneyGoesOut: "Recurring subscription billing and enterprise licenses are paid to offshore headquarters.",
    indiaOptions: "Zoho and Indian SaaS alternatives can replace some workflows fully.",
    honestyNote: "Best immediate switching category where quality is comparable for your use case.",
  },
  {
    id: "app-store-fees",
    category: "App ecosystem fees",
    outflowType: "digital-services",
    commonSpendUse: "In-app purchases and premium mobile apps",
    importDependency: "high",
    brandExamples: ["Apple App Store", "Google Play billing"],
    whyMoneyGoesOut: "Platform fees and commissions are tied to foreign app-store rails.",
    indiaOptions: "UPI web-checkout and direct subscriptions where available.",
    honestyNote: "Even Indian apps can leak value if billed via foreign platform rails.",
  },
  {
    id: "premium-sportswear",
    category: "Premium sportswear",
    outflowType: "consumer-goods",
    commonSpendUse: "Lifestyle and performance shoes",
    importDependency: "medium",
    brandExamples: ["Nike", "Adidas", "Puma"],
    whyMoneyGoesOut: "Brand premium, licensing, and design ownership sit with global parent companies.",
    indiaOptions: "Campus, Red Tape, HRX, Performax are improving in mass and mid tiers.",
    honestyNote: "High-end performance categories still stronger with global players.",
  },
  {
    id: "premium-audio",
    category: "Premium audio",
    outflowType: "electronics",
    commonSpendUse: "ANC headphones and premium earbuds",
    importDependency: "high",
    brandExamples: ["Sony", "Bose", "Sennheiser", "Apple AirPods"],
    whyMoneyGoesOut: "Acoustic IP, chip integration, and premium brand value are foreign-owned.",
    indiaOptions: "boAt and Noise are strong in budget-to-mid tiers but not top-tier ANC leaders yet.",
    honestyNote: "Budget commute audio is easier to localize than audiophile tiers.",
  },
  {
    id: "fmcg-personal-care",
    category: "Imported personal care & beauty",
    outflowType: "consumer-goods",
    commonSpendUse: "Shampoo, skincare, deodorant",
    importDependency: "medium",
    brandExamples: ["L'Oreal", "Unilever (Dove)", "P&G (Head & Shoulders)", "Nivea"],
    whyMoneyGoesOut: "Global FMCG parents earn royalties and margins on formulations even when products are made in India.",
    indiaOptions: "Himalaya, Mamaearth, Biotique, Patanjali, and many D2C Indian brands cover daily care well.",
    honestyNote: "Check ownership - some Indian labels are licensed by MNCs.",
  },
  {
    id: "packaged-foods-snacks",
    category: "Imported snacks & beverages",
    outflowType: "consumer-goods",
    commonSpendUse: "Chips, chocolates, soft drinks",
    importDependency: "medium",
    brandExamples: ["Coca-Cola", "PepsiCo", "Mondelez (Cadbury)", "Nestle (Maggi/Kits)"],
    whyMoneyGoesOut: "Brand IP, marketing spend, and profit repatriation flow to global HQs.",
    indiaOptions: "Haldiram's, Bikaji, Paper Boat, Amul, and regional brands keep more value local.",
    honestyNote: "Many items are manufactured here; the outflow is often profit and IP, not the physical good.",
  },
  {
    id: "pharma-devices",
    category: "Medical devices & implants",
    outflowType: "electronics",
    commonSpendUse: "Stents, implants, diagnostic machines",
    importDependency: "very-high",
    brandExamples: ["Medtronic", "Abbott", "Siemens Healthineers", "GE HealthCare"],
    whyMoneyGoesOut: "High-tech devices and implants are heavily import-dependent with long R&D cycles abroad.",
    indiaOptions: "Make in India push is growing; many hospitals still rely on imported devices for critical care.",
    honestyNote: "Health outcomes matter more than origin - but it is a major forex lane.",
  },
  {
    id: "gold-jewellery",
    category: "Gold jewellery demand",
    outflowType: "luxury",
    commonSpendUse: "Weddings and festival gold buying",
    importDependency: "very-high",
    brandExamples: ["Imported bullion supply chain"],
    whyMoneyGoesOut: "India is among the largest gold importers; a large share of jewellery demand is met via imported metal.",
    indiaOptions: "Hallmarked Indian jewellers use the same global price; reducing discretionary gold import is the lever.",
    honestyNote: "Cultural demand makes this one of the hardest categories to swap locally.",
  },
  {
    id: "luxury-watches",
    category: "Luxury watches",
    outflowType: "luxury",
    commonSpendUse: "Premium gifting and status purchases",
    importDependency: "high",
    brandExamples: ["Rolex", "Omega", "TAG Heuer", "Casio (premium lines)"],
    whyMoneyGoesOut: "Swiss and Japanese watchmakers capture design IP and retail margins offshore.",
    indiaOptions: "Titan, Fastrack, and Indian microbrands cover mid tiers; ultra-luxury remains import-led.",
    honestyNote: "Discretionary category with near-total foreign brand dominance at the top.",
  },
  {
    id: "streaming-video",
    category: "Global streaming subscriptions",
    outflowType: "digital-services",
    commonSpendUse: "Netflix, Prime Video, Disney+ Hotstar premium",
    importDependency: "high",
    brandExamples: ["Netflix", "Amazon Prime Video", "Apple TV+"],
    whyMoneyGoesOut: "Content licensing fees and platform economics are paid to foreign rights holders.",
    indiaOptions: "JioCinema, Zee5, SonyLIV host strong Indian catalogues; mix based on what you watch.",
    honestyNote: "Hotstar is Indian-operated but still licenses a lot of global content.",
  },
  {
    id: "ev-batteries",
    category: "EV batteries & cells",
    outflowType: "electronics",
    commonSpendUse: "Electric cars and two-wheelers",
    importDependency: "very-high",
    brandExamples: ["CATL", "LG Energy", "Panasonic", "Samsung SDI"],
    whyMoneyGoesOut: "Cell chemistry and pack IP are concentrated in East Asia and the West.",
    indiaOptions: "Ola, Ather, Tata EVs assemble locally but still import cells; PLI is building capacity.",
    honestyNote: "Buying Indian EV brands helps jobs and assembly; cells may still be imported for years.",
  },
];
