import type { SongProject } from "./types";

export function buildMarkdownPackage(project: SongProject): string {
  const a = project.analysis;
  if (!a) return "# No analysis yet\n";

  const structure = a.structure
    .filter((s) => s.status !== "rejected")
    .map((s) => `### ${s.label}\n${s.content}`)
    .join("\n\n");

  const hooks = a.hooks
    .filter((h) => h.status === "accepted")
    .map((h) => `- ${h.text}`)
    .join("\n");

  return `# ${project.meta.projectName}

**Genre:** ${project.meta.genre} | **Language:** ${project.meta.primaryLanguage} | **Tempo:** ${project.meta.tempo}
**Moods:** ${project.meta.moods.join(", ")} | **Energy:** ${project.meta.energy}/10

## Final Lyrics
${a.finalLyrics}

## Song Structure
${structure}

## Chords
**Progression:** ${a.chords.progression}
**Beginner:** ${a.chords.beginner}
**Advanced:** ${a.chords.advanced}
**Capo:** ${a.chords.capo}

## Arrangement
${a.arrangement.map((x) => `- **${x.section}:** ${x.notes}`).join("\n")}

## Accepted Hooks
${hooks || "_None selected_"}

## Vocal Guidance
${a.vocalGuidance}

## Recording Notes
${a.recordingNotes}

## Producer Brief
${a.producerBrief}

---
_Generated by AI Songwriting Studio — cooltoolsbykul.com/songwriter_
`;
}

export function downloadText(filename: string, content: string, mime = "text/markdown") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
