import type { BulkPack } from "./helpers";
import { adj, conn, n, tw, vAre, vEre, vIre } from "./helpers";

export const BULK_L2: BulkPack = {
  verbs: [
    vAre("ballare", "ballare", "ball", "to dance", 2),
    vAre("cantare", "cantare", "cant", "to sing", 2),
    vAre("suonare", "suonare", "suon", "to play (instrument)", 2),
    vAre("viaggiare", "viaggiare", "viagg", "to travel", 2),
    vAre("visitare", "visitare", "visit", "to visit", 2),
    vAre("nuotare", "nuotare", "nuot", "to swim", 2),
    vAre("lavare", "lavare", "lav", "to wash", 2),
    vAre("pulire", "pulire", "pul", "to clean", 2),
    vIre("vestire", "vestire", "vest", "to dress", 2),
    vAre("indossare", "indossare", "indoss", "to wear", 2),
    vAre("tagliare", "tagliare", "tagli", "to cut", 2),
    vAre("disegnare", "disegnare", "disegn", "to draw", 2),
    vAre("fotografare", "fotografare", "fotograf", "to photograph", 2),
    vEre("crescere", "crescere", "cresc", "to grow", 2),
    vAre("pescare", "pescare", "pesc", "to fish", 2),
    vAre("sciare", "sciare", "sci", "to ski", 2),
    vAre("cucinare", "cucinare", "cucin", "to cook", 2),
    vAre("comprare", "comprare", "compr", "to buy", 2),
    vAre("vendere", "vendere", "vend", "to sell", 2),
    vAre("pagare", "pagare", "pag", "to pay", 2),
    vAre("guidare", "guidare", "guid", "to drive", 2),
    vAre("camminare", "camminare", "cammin", "to walk", 2),
    vAre("correre", "correre", "corr", "to run", 2),
    vAre("saltare", "saltare", "salt", "to jump", 2),
    vAre("dormire", "dormire", "dorm", "to sleep", 2),
    vAre("svegliare", "svegliare", "svegli", "to wake", 2),
    vAre("sognare", "sognare", "sogn", "to dream", 2),
    vAre("ridere", "ridere", "rid", "to laugh", 2),
    vAre("piangere", "piangere", "piang", "to cry", 2),
    vAre("abbracciare", "abbracciare", "abbracci", "to hug", 2),
    vAre("baciare", "baciare", "baci", "to kiss", 2),
    vAre("invitare", "invitare", "invit", "to invite", 2),
  ],
  nouns: [
  n("negozio", "negozio", "shop", "m", "place"),
  n("mercato", "mercato", "market", "m", "place"),
  n("farmacia", "farmacia", "pharmacy", "f", "health"),
  n("ospedale", "ospedale", "hospital", "m", "health"),
  n("dottore", "dottore", "doctor", "m", "person"),
  n("infermiera", "infermiera", "nurse", "f", "person"),
  n("soldi", "soldi", "money", "m", "object"),
  n("banca", "banca", "bank", "f", "place"),
  n("fabbrica", "fabbrica", "factory", "f", "work"),
  n("azienda", "azienda", "company", "f", "work"),
  n("collega", "collega", "colleague", "m", "person"),
  n("capo", "capo", "boss", "m", "person"),
  n("cliente", "cliente", "client", "m", "person"),
  n("vicino", "vicino", "neighbor", "m", "person"),
  n("vicina", "vicina", "neighbor (f)", "f", "person"),
  n("nazione", "nazione", "nation", "f", "place"),
  n("sole", "sole", "sun", "m", "nature"),
  n("luna", "luna", "moon", "f", "nature"),
  n("cielo", "cielo", "sky", "m", "nature"),
  n("terra", "terra", "earth", "f", "nature"),
  n("fiume", "fiume", "river", "m", "nature"),
  n("lago", "lago", "lake", "m", "nature"),
  n("montagna", "montagna", "mountain", "f", "nature"),
  n("pioggia", "pioggia", "rain", "f", "nature"),
  n("neve", "neve", "snow", "f", "nature"),
  n("vento", "vento", "wind", "m", "nature"),
  n("primavera", "primavera", "spring", "f", "time"),
  n("estate", "estate", "summer", "f", "time"),
  n("autunno", "autunno", "autumn", "m", "time"),
  n("inverno", "inverno", "winter", "m", "time"),
  n("settimana", "settimana", "week", "f", "time"),
  n("mese", "mese", "month", "m", "time"),
  n("minuto", "minuto", "minute", "m", "time"),
  n("mattino", "mattino", "morning", "m", "time"),
  n("pomeriggio", "pomeriggio", "afternoon", "m", "time"),
  n("festa", "festa", "party", "f", "abstract"),
  n("regalo", "regalo", "gift", "m", "object"),
  n("lettera", "lettera", "letter", "f", "object"),
  n("musica", "musica", "music", "f", "abstract"),
  n("canzone", "canzone", "song", "f", "abstract"),
  n("film", "film", "film", "m", "abstract"),
  n("sport", "sport", "sport", "m", "abstract"),
  n("calcio", "calcio", "football", "m", "abstract"),
  n("bicicletta", "bicicletta", "bicycle", "f", "object"),
  n("aereo", "aereo", "airplane", "m", "travel"),
  n("aeroporto", "aeroporto", "airport", "m", "travel"),
  n("biglietto", "biglietto", "ticket", "m", "travel"),
  n("valigia", "valigia", "suitcase", "f", "travel"),
  n("vacanza", "vacanza", "vacation", "f", "travel"),
  n("mappa", "mappa", "map", "f", "object"),
  n("destra", "destra", "right", "f", "abstract"),
  n("sinistra", "sinistra", "left", "f", "abstract"),
  n("centro", "centro", "center", "m", "place"),
  n("bagno", "bagno", "bathroom", "m", "home"),
  n("letto", "letto", "bed", "m", "home"),
  n("forchetta", "forchetta", "fork", "f", "object"),
  n("cucchiaio", "cucchiaio", "spoon", "m", "object"),
  n("piatto", "piatto", "plate", "m", "object"),
  n("bicchiere", "bicchiere", "glass", "m", "object"),
  n("frigorifero", "frigorifero", "fridge", "m", "object"),
  n("divano", "divano", "sofa", "m", "home"),
  n("lampada", "lampada", "lamp", "f", "object"),
  n("rumore", "rumore", "noise", "m", "abstract"),
  n("voce", "voce", "voice", "f", "abstract"),
  n("colore", "colore", "color", "m", "abstract"),
  n("rosso", "rosso", "red", "m", "abstract"),
  n("verde", "verde", "green", "m", "abstract"),
  n("numero", "numero", "number", "m", "abstract"),
  n("motivo", "motivo", "reason", "m", "abstract"),
  n("progetto", "progetto", "project", "m", "work"),
  n("salute", "salute", "health", "f", "health"),
  n("medicina", "medicina", "medicine", "f", "health"),
  n("dolore", "dolore", "pain", "m", "health"),
  n("famiglia", "famiglia", "family", "f", "person"),
  n("marito", "marito", "husband", "m", "person"),
  n("moglie", "moglie", "wife", "f", "person"),
  n("figlio", "figlio", "son", "m", "person"),
  n("figlia", "figlia", "daughter", "f", "person"),
  n("nonno", "nonno", "grandfather", "m", "person"),
  n("nonna", "nonna", "grandmother", "f", "person"),
  n("zio", "zio", "uncle", "m", "person"),
  n("zia", "zia", "aunt", "f", "person"),
  n("cugino", "cugino", "cousin (m)", "m", "person"),
  n("cugina", "cugina", "cousin (f)", "f", "person"),
  n("bambino", "bambino", "child (m)", "m", "person"),
  n("bambina", "bambina", "child (f)", "f", "person"),
  n("ragazzo", "ragazzo", "boy", "m", "person"),
  n("ragazza", "ragazza", "girl", "f", "person"),
  n("uomo", "uomo", "man", "m", "person"),
  n("donna", "donna", "woman", "f", "person"),
  n("sposa", "sposa", "bride", "f", "person"),
  n("sposo", "sposo", "groom", "m", "person"),
  n("fidanzato", "fidanzato", "boyfriend", "m", "person"),
  n("fidanzata", "fidanzata", "girlfriend", "f", "person"),
  n("neonato", "neonato", "newborn", "m", "person"),
  n("anziano", "anziano", "elderly man", "m", "person"),
  n("anziana", "anziana", "elderly woman", "f", "person"),
  n("vicinato", "vicinato", "neighborhood", "m", "place"),
  n("strada", "strada", "street", "f", "place"),
  n("via", "via", "road", "f", "place"),
  n("incrocio", "incrocio", "intersection", "m", "place"),
  n("semaforo", "semaforo", "traffic light", "m", "object"),
  n("parcheggio", "parcheggio", "parking", "m", "place"),
  n("stazione", "stazione", "station", "f", "travel"),
  n("fermata", "fermata", "stop", "f", "travel"),
  n("autobus", "autobus", "bus", "m", "travel"),
  n("treno", "treno", "train", "m", "travel"),
  n("metro", "metro", "subway", "f", "travel"),
  n("taxi", "taxi", "taxi", "m", "travel"),
  n("porto", "porto", "port", "m", "travel"),
  n("spiaggia", "spiaggia", "beach", "f", "nature"),
  n("isola", "isola", "island", "f", "nature"),
  n("costa", "costa", "coast", "f", "nature"),
  n("roccia", "roccia", "rock", "f", "nature"),
  n("sabbia", "sabbia", "sand", "f", "nature"),
  n("albero", "albero", "tree", "m", "nature"),
  n("fiore", "fiore", "flower", "m", "nature"),
  n("erba", "erba", "grass", "f", "nature"),
  n("animale", "animale", "animal", "m", "nature"),
  n("cane", "cane", "dog", "m", "nature"),
  n("gatto", "gatto", "cat", "m", "nature"),
  n("uccello", "uccello", "bird", "m", "nature"),
  n("pesce", "pesce", "fish", "m", "nature"),
  n("insetto", "insetto", "insect", "m", "nature"),
  n("farfalla", "farfalla", "butterfly", "f", "nature"),
  n("ape", "ape", "bee", "f", "nature"),
  n("formica", "formica", "ant", "f", "nature"),
  ],
  adjectives: [
    adj("stanco", "tired", "stanco", "stanca", "stanchi", "stanche", 2),
    adj("affamato", "hungry", "affamato", "affamata", "affamati", "affamate", 2),
    adj("malato", "sick", "malato", "malata", "malati", "malate", 2),
    adj("sano", "healthy", "sano", "sana", "sani", "sane", 2),
    adj("veloce", "fast", "veloce", "veloce", "veloci", "veloci", 2),
    adj("lento", "slow", "lento", "lenta", "lenti", "lente", 2),
    adj("facile", "easy", "facile", "facile", "facili", "facili", 2),
    adj("difficile", "hard", "difficile", "difficile", "difficili", "difficili", 2),
    adj("caro", "dear/expensive", "caro", "cara", "cari", "care", 2),
    adj("economico", "cheap", "economico", "economica", "economici", "economiche", 2),
    adj("pulito", "clean", "pulito", "pulita", "puliti", "pulite", 2),
    adj("sporco", "dirty", "sporco", "sporca", "sporchi", "sporche", 2),
    adj("vuoto", "empty", "vuoto", "vuota", "vuoti", "vuote", 2),
    adj("pieno", "full", "pieno", "piena", "pieni", "piene", 2),
  ],
  timeWords: [
    tw("presto", "presto", "early/soon", 2),
    tw("tardi", "tardi", "late", 2),
    tw("spesso", "spesso", "often", 2),
    tw("raramente", "raramente", "rarely", 2),
    tw("qualche_volta", "qualche volta", "sometimes", 2),
    tw("ogni_giorno", "ogni giorno", "every day", 2),
  ],
  connectors: [
    conn("anche", "anche", "also", 2),
    conn("quindi", "quindi", "therefore", 2),
    conn("pero", "però", "however", 2),
    conn("oppure", "oppure", "or else", 2),
    conn("infatti", "infatti", "in fact", 2),
    conn("altrimenti", "altrimenti", "otherwise", 2),
  ],
};
