import type { BulkPack } from "./helpers";
import { adj, conn, n, tw, vAre, vEre, vIre } from "./helpers";

export const BULK_L3: BulkPack = {
  verbs: [
    vAre("discutere", "discutere", "discut", "to discuss", 3),
    vAre("convincere", "convincere", "convinc", "to convince", 3),
    vAre("suggerire", "suggerire", "sugger", "to suggest", 3),
    vAre("consigliare", "consigliare", "consigli", "to advise", 3),
    vAre("ringraziare", "ringraziare", "ringrazi", "to thank", 3),
    vAre("scusare", "scusare", "scus", "to apologize", 3),
    vAre("perdonare", "perdonare", "perdon", "to forgive", 3),
    vAre("rispettare", "rispettare", "rispett", "to respect", 3),
    vAre("mentire", "mentire", "ment", "to lie", 3),
    vAre("nascondere", "nascondere", "nascond", "to hide", 3),
    vAre("scoprire", "scoprire", "scop", "to discover", 3),
    vAre("creare", "creare", "cre", "to create", 3),
    vAre("costruire", "costruire", "costru", "to build", 3),
    vAre("riparare", "riparare", "ripar", "to repair", 3),
    vAre("organizzare", "organizzare", "organizz", "to organize", 3),
    vAre("preparare", "preparare", "prepar", "to prepare", 3),
    vAre("prenotare", "prenotare", "prenot", "to book", 3),
    vAre("confermare", "confermare", "conferm", "to confirm", 3),
    vAre("cancellare", "cancellare", "cancell", "to cancel", 3),
    vAre("spiegare", "spiegare", "spieg", "to explain", 3),
    vAre("descrivere", "descrivere", "descriv", "to describe", 3),
    vAre("raccontare", "raccontare", "raccont", "to tell", 3),
    vAre("ricordare", "ricordare", "ricord", "to remember", 3),
    vAre("dimenticare", "dimenticare", "dimentic", "to forget", 3),
    vAre("immaginare", "immaginare", "immagin", "to imagine", 3),
    vAre("sperare", "sperare", "sper", "to hope", 3),
    vAre("temiere", "temere", "tem", "to fear", 3),
    vAre("preferire", "preferire", "prefer", "to prefer", 3),
  ],
  nouns: [
  n("sentimento", "sentimento", "feeling", "m", "abstract"),
  n("emozione", "emozione", "emotion", "f", "abstract"),
  n("rabbia", "rabbia", "anger", "f", "abstract"),
  n("gioia", "gioia", "joy", "f", "abstract"),
  n("tristezza", "tristezza", "sadness", "f", "abstract"),
  n("sorriso", "sorriso", "smile", "m", "abstract"),
  n("lacrima", "lacrima", "tear", "f", "abstract"),
  n("anima", "anima", "soul", "f", "abstract"),
  n("mente", "mente", "mind", "f", "abstract"),
  n("pensiero", "pensiero", "thought", "m", "abstract"),
  n("idea", "idea", "idea", "f", "abstract"),
  n("opinione", "opinione", "opinion", "f", "abstract"),
  n("dubbio", "dubbio", "doubt", "m", "abstract"),
  n("verita", "verità", "truth", "f", "abstract"),
  n("bugia", "bugia", "lie", "f", "abstract"),
  n("segreto", "segreto", "secret", "m", "abstract"),
  n("fiducia", "fiducia", "trust", "f", "abstract"),
  n("rispetto", "rispetto", "respect", "m", "abstract"),
  n("liberta", "libertà", "freedom", "f", "abstract"),
  n("giustizia", "giustizia", "justice", "f", "abstract"),
  n("diritto", "diritto", "right (legal)", "m", "abstract"),
  n("legge", "legge", "law", "f", "abstract"),
  n("regola", "regola", "rule", "f", "abstract"),
  n("dovere", "dovere", "duty", "m", "abstract"),
  n("responsabilita", "responsabilità", "responsibility", "f", "abstract"),
  n("scusa", "scusa", "apology", "f", "abstract"),
  n("promessa", "promessa", "promise", "f", "abstract"),
  n("accordo", "accordo", "agreement", "m", "abstract"),
  n("contratto", "contratto", "contract", "m", "work"),
  n("riunione", "riunione", "meeting", "f", "work"),
  n("conferenza", "conferenza", "conference", "f", "work"),
  n("documento", "documento", "document", "m", "work"),
  n("firma", "firma", "signature", "f", "work"),
  n("pacco", "pacco", "package", "m", "object"),
  n("ordine", "ordine", "order", "m", "work"),
  n("fattura", "fattura", "invoice", "f", "work"),
  n("prezzo", "prezzo", "price", "m", "work"),
  n("costo", "costo", "cost", "m", "work"),
  n("profitto", "profitto", "profit", "m", "work"),
  n("conto", "conto", "account", "m", "work"),
  n("moneta", "moneta", "coin", "f", "object"),
  n("banconota", "banconota", "banknote", "f", "object"),
  n("stipendio", "stipendio", "salary", "m", "work"),
  n("colloquio", "colloquio", "interview", "m", "work"),
  n("esperienza", "esperienza", "experience", "f", "work"),
  n("competenza", "competenza", "skill", "f", "work"),
  n("corso", "corso", "course", "m", "work"),
  n("lezione", "lezione", "lesson", "f", "work"),
  n("esame", "esame", "exam", "m", "work"),
  n("voto", "voto", "grade", "m", "work"),
  n("diploma", "diploma", "diploma", "m", "work"),
  n("laurea", "laurea", "degree", "f", "work"),
  n("ricerca", "ricerca", "research", "f", "work"),
  n("tecnologia", "tecnologia", "technology", "f", "abstract"),
  n("internet", "internet", "internet", "m", "communication"),
  n("sito", "sito", "website", "m", "communication"),
  n("password", "password", "password", "f", "communication"),
  n("foto", "foto", "photo", "f", "communication"),
  n("video", "video", "video", "m", "communication"),
  n("muro", "muro", "wall", "m", "place"),
  n("tetto", "tetto", "roof", "m", "place"),
  n("giardino", "giardino", "garden", "m", "place"),
  n("balcone", "balcone", "balcony", "m", "home"),
  n("terrazza", "terrazza", "terrace", "f", "home"),
  n("chiave", "chiave", "key", "f", "object"),
  n("sicurezza", "sicurezza", "security", "f", "abstract"),
  n("pericolo", "pericolo", "danger", "m", "abstract"),
  n("rischio", "rischio", "risk", "m", "abstract"),
  n("incidente", "incidente", "incident", "m", "abstract"),
  n("emergenza", "emergenza", "emergency", "f", "abstract"),
  n("aiuto", "aiuto", "help", "m", "abstract"),
  n("polizia", "polizia", "police", "f", "abstract"),
  n("ambulanza", "ambulanza", "ambulance", "f", "object"),
  n("avvocato", "avvocato", "lawyer", "m", "person"),
  n("giudice", "giudice", "judge", "m", "person"),
  n("pace", "pace", "peace", "f", "abstract"),
  n("guerra", "guerra", "war", "f", "abstract"),
  n("esercito", "esercito", "army", "m", "abstract"),
  n("soldato", "soldato", "soldier", "m", "person"),
  n("confine", "confine", "border", "m", "place"),
  n("visto", "visto", "visa", "m", "travel"),
  n("passaporto", "passaporto", "passport", "m", "travel"),
  ],
  adjectives: [
    adj("arrabbiato", "angry", "arrabbiato", "arrabbiata", "arrabbiati", "arrabbiate", 3),
    adj("nervoso", "nervous", "nervoso", "nervosa", "nervosi", "nervose", 3),
    adj("calmo", "calm", "calmo", "calma", "calmi", "calme", 3),
    adj("possibile", "possible", "possibile", "possibile", "possibili", "possibili", 3),
    adj("necessario", "necessary", "necessario", "necessaria", "necessari", "necessarie", 3),
    adj("utile", "useful", "utile", "utile", "utili", "utili", 3),
    adj("inutile", "useless", "inutile", "inutile", "inutili", "inutili", 3),
    adj("importante", "important", "importante", "importante", "importanti", "importanti", 3),
    adj("interessante", "interesting", "interessante", "interessante", "interessanti", "interessanti", 3),
  ],
  timeWords: [
    tw("subito", "subito", "immediately", 3),
    tw("ancora", "ancora", "still/again", 3),
    tw("gia", "già", "already", 3),
    tw("appena", "appena", "just/barely", 3),
    tw("prima", "prima", "before", 3),
    tw("dopo", "dopo", "after", 3),
  ],
  connectors: [
    conn("mentre", "mentre", "while", 3),
    conn("nonostante", "nonostante", "despite", 3),
    conn("affinche", "affinché", "so that", 3),
    conn("sebbene", "sebbene", "although", 3),
  ],
};
