import type { BulkPack } from "./helpers";
import { adj, conn, n, tw, vAre, vEre, vIre } from "./helpers";

export const BULK_L4: BulkPack = {
  verbs: [
    vAre("programmare", "programmare", "programm", "to program", 4),
    vAre("installare", "installare", "install", "to install", 4),
    vAre("scaricare", "scaricare", "scaric", "to download", 4),
    vAre("caricare", "caricare", "caric", "to upload/charge", 4),
    vAre("collegare", "collegare", "colleg", "to connect", 4),
    vAre("condividere", "condividere", "condivid", "to share", 4),
    vAre("pubblicare", "pubblicare", "pubblic", "to publish", 4),
    vAre("stampare", "stampare", "stamp", "to print", 4),
    vAre("registrare", "registrare", "registr", "to record", 4),
    vAre("modificare", "modificare", "modific", "to modify", 4),
    vAre("eliminare", "eliminare", "elimin", "to delete", 4),
    vAre("verificare", "verificare", "verific", "to verify", 4),
    vAre("confrontare", "confrontare", "confront", "to compare", 4),
    vAre("misurare", "misurare", "misur", "to measure", 4),
    vAre("calcolare", "calcolare", "calcol", "to calculate", 4),
    vAre("stimare", "stimare", "stim", "to estimate", 4),
  ],
  nouns: [
  n("societa", "società", "society", "f", "abstract"),
  n("cultura", "cultura", "culture", "f", "abstract"),
  n("tradizione", "tradizione", "tradition", "f", "abstract"),
  n("religione", "religione", "religion", "f", "abstract"),
  n("chiesa", "chiesa", "church", "f", "place"),
  n("prete", "prete", "priest", "m", "person"),
  n("preghiera", "preghiera", "prayer", "f", "abstract"),
  n("cerimonia", "cerimonia", "ceremony", "f", "abstract"),
  n("matrimonio", "matrimonio", "wedding", "m", "abstract"),
  n("funerale", "funerale", "funeral", "m", "abstract"),
  n("nascita", "nascita", "birth", "f", "abstract"),
  n("morte", "morte", "death", "f", "abstract"),
  n("eta", "età", "age", "f", "abstract"),
  n("generazione", "generazione", "generation", "f", "abstract"),
  n("infanzia", "infanzia", "childhood", "f", "abstract"),
  n("memoria", "memoria", "memory", "f", "abstract"),
  n("attenzione", "attenzione", "attention", "f", "abstract"),
  n("pazienza", "pazienza", "patience", "f", "abstract"),
  n("stress", "stress", "stress", "m", "abstract"),
  n("ansia", "ansia", "anxiety", "f", "abstract"),
  n("terapia", "terapia", "therapy", "f", "health"),
  n("psicologo", "psicologo", "psychologist", "m", "person"),
  n("farmaco", "farmaco", "medicine", "m", "health"),
  n("ricetta", "ricetta", "prescription", "f", "health"),
  n("operazione", "operazione", "operation", "f", "health"),
  n("analisi", "analisi", "analysis", "f", "health"),
  n("sangue", "sangue", "blood", "m", "body"),
  n("polmone", "polmone", "lung", "m", "body"),
  n("fegato", "fegato", "liver", "m", "body"),
  n("rene", "rene", "kidney", "m", "body"),
  n("stomaco", "stomaco", "stomach", "m", "body"),
  n("pelle", "pelle", "skin", "f", "body"),
  n("osso", "osso", "bone", "m", "body"),
  n("muscolo", "muscolo", "muscle", "m", "body"),
  n("cervello", "cervello", "brain", "m", "body"),
  n("dente", "dente", "tooth", "m", "body"),
  n("lingua", "lingua", "tongue/language", "f", "body"),
  n("gola", "gola", "throat", "f", "body"),
  n("naso", "naso", "nose", "m", "body"),
  n("orecchio", "orecchio", "ear", "m", "body"),
  n("labbro", "labbro", "lip", "m", "body"),
  n("spalla", "spalla", "shoulder", "f", "body"),
  n("ginocchio", "ginocchio", "knee", "m", "body"),
  n("caviglia", "caviglia", "ankle", "f", "body"),
  n("schiena", "schiena", "back", "f", "body"),
  n("petto", "petto", "chest", "m", "body"),
  n("universita", "università", "university", "f", "work"),
  n("facolta", "facoltà", "faculty", "f", "work"),
  n("professore", "professore", "professor", "m", "person"),
  n("studente", "studente", "student", "m", "person"),
  n("studentessa", "studentessa", "student (f)", "f", "person"),
  n("biblioteca", "biblioteca", "library", "f", "place"),
  n("laboratorio", "laboratorio", "laboratory", "m", "work"),
  n("esperimento", "esperimento", "experiment", "m", "work"),
  n("teoria", "teoria", "theory", "f", "abstract"),
  n("pratica", "pratica", "practice", "f", "abstract"),
  n("metodo", "metodo", "method", "m", "abstract"),
  n("risultato", "risultato", "result", "m", "abstract"),
  n("obiettivo", "obiettivo", "goal", "m", "abstract"),
  n("strategia", "strategia", "strategy", "f", "abstract"),
  n("soluzione", "soluzione", "solution", "f", "abstract"),
  n("problema", "problema", "problem", "m", "abstract"),
  n("sfida", "sfida", "challenge", "f", "abstract"),
  n("opportunita", "opportunità", "opportunity", "f", "abstract"),
  n("crisi", "crisi", "crisis", "f", "abstract"),
  n("cambiamento", "cambiamento", "change", "m", "abstract"),
  n("sviluppo", "sviluppo", "development", "m", "abstract"),
  n("progresso", "progresso", "progress", "m", "abstract"),
  n("innovazione", "innovazione", "innovation", "f", "abstract"),
  n("creativita", "creatività", "creativity", "f", "abstract"),
  n("immaginazione", "immaginazione", "imagination", "f", "abstract"),
  n("fantasia", "fantasia", "fantasy", "f", "abstract"),
  n("realta", "realtà", "reality", "f", "abstract"),
  n("sogno", "sogno", "dream", "m", "abstract"),
  n("incubo", "incubo", "nightmare", "m", "abstract"),
  n("speranza", "speranza", "hope", "f", "abstract"),
  n("delusione", "delusione", "disappointment", "f", "abstract"),
  n("sorpresa", "sorpresa", "surprise", "f", "abstract"),
  n("curiosita", "curiosità", "curiosity", "f", "abstract"),
  n("entusiasmo", "entusiasmo", "enthusiasm", "m", "abstract"),
  n("motivazione", "motivazione", "motivation", "f", "abstract"),
  n("ambizione", "ambizione", "ambition", "f", "abstract"),
  n("successo", "successo", "success", "m", "abstract"),
  n("fallimento", "fallimento", "failure", "m", "abstract"),
  n("tentativo", "tentativo", "attempt", "m", "abstract"),
  n("sforzo", "sforzo", "effort", "m", "abstract"),
  n("abitudine", "abitudine", "habit", "f", "abstract"),
  n("routine", "routine", "routine", "f", "abstract"),
  n("ritmo", "ritmo", "rhythm", "m", "abstract"),
  n("silenzio", "silenzio", "silence", "m", "abstract"),
  n("paesaggio", "paesaggio", "landscape", "m", "nature"),
  n("orizzonte", "orizzonte", "horizon", "m", "nature"),
  n("tramonto", "tramonto", "sunset", "m", "nature"),
  n("alba", "alba", "dawn", "f", "nature"),
  n("nebbia", "nebbia", "fog", "f", "nature"),
  n("grandine", "grandine", "hail", "f", "nature"),
  n("tuono", "tuono", "thunder", "m", "nature"),
  n("fulmine", "fulmine", "lightning", "m", "nature"),
  n("arcobaleno", "arcobaleno", "rainbow", "m", "nature"),
  n("stella", "stella", "star", "f", "nature"),
  n("pianeta", "pianeta", "planet", "m", "nature"),
  n("galassia", "galassia", "galaxy", "f", "nature"),
  n("universo", "universo", "universe", "m", "nature"),
  n("energia", "energia", "energy", "f", "abstract"),
  n("materia", "materia", "matter", "f", "abstract"),
  n("atomo", "atomo", "atom", "m", "abstract"),
  n("molecola", "molecola", "molecule", "f", "abstract"),
  n("elemento", "elemento", "element", "m", "abstract"),
  ],
  adjectives: [
    adj("digitale", "digital", "digitale", "digitale", "digitali", "digitali", 4),
    adj("tecnico", "technical", "tecnico", "tecnica", "tecnici", "tecniche", 4),
    adj("pratico", "practical", "pratico", "pratica", "pratici", "pratiche", 4),
    adj("teorico", "theoretical", "teorico", "teorica", "teorici", "teoriche", 4),
    adj("scientifico", "scientific", "scientifico", "scientifica", "scientifici", "scientifiche", 4),
  ],
  timeWords: [
    tw("recentemente", "recentemente", "recently", 4),
    tw("attualmente", "attualmente", "currently", 4),
    tw("precedentemente", "precedentemente", "previously", 4),
    tw("eventualmente", "eventualmente", "eventually", 4),
  ],
  connectors: [
    conn("cioe", "cioè", "that is", 4),
    conn("ovvero", "ovvero", "namely", 4),
    conn("inoltre", "inoltre", "furthermore", 4),
    conn("comunque", "comunque", "anyway", 4),
  ],
};
