import type { BulkPack } from "./helpers";
import { adj, conn, n, tw, vAre, vEre, vIre } from "./helpers";

export const BULK_L5: BulkPack = {
  verbs: [
    vAre("negoziare", "negoziare", "negozi", "to negotiate", 5),
    vAre("governare", "governare", "govern", "to govern", 5),
    vAre("rappresentare", "rappresentare", "rappresent", "to represent", 5),
    vAre("sostenere", "sostenere", "sosteng", "to support", 5),
    vAre("proporre", "proporre", "prop", "to propose", 5),
    vAre("approvare", "approvare", "approv", "to approve", 5),
    vAre("rifiutare", "rifiutare", "rifiut", "to refuse", 5),
    vAre("amministrare", "amministrare", "amministr", "to administer", 5),
    vAre("regolamentare", "regolamentare", "regolament", "to regulate", 5),
    vAre("finanziare", "finanziare", "finanzi", "to finance", 5),
    vAre("investire", "investire", "invest", "to invest", 5),
    vAre("quotare", "quotare", "quot", "to list (stock)", 5),
  ],
  nouns: [
  n("filosofia", "filosofia", "philosophy", "f", "abstract"),
  n("scienza", "scienza", "science", "f", "abstract"),
  n("matematica", "matematica", "mathematics", "f", "abstract"),
  n("fisica", "fisica", "physics", "f", "abstract"),
  n("chimica", "chimica", "chemistry", "f", "abstract"),
  n("biologia", "biologia", "biology", "f", "abstract"),
  n("storia", "storia", "history", "f", "abstract"),
  n("geografia", "geografia", "geography", "f", "abstract"),
  n("letteratura", "letteratura", "literature", "f", "abstract"),
  n("poesia", "poesia", "poetry", "f", "abstract"),
  n("romanzo", "romanzo", "novel", "m", "abstract"),
  n("autore", "autore", "author", "m", "person"),
  n("poeta", "poeta", "poet", "m", "person"),
  n("artista", "artista", "artist", "m", "person"),
  n("pittore", "pittore", "painter", "m", "person"),
  n("scultura", "scultura", "sculpture", "f", "abstract"),
  n("architettura", "architettura", "architecture", "f", "abstract"),
  n("moda", "moda", "fashion", "f", "abstract"),
  n("stile", "stile", "style", "m", "abstract"),
  n("tendenza", "tendenza", "trend", "f", "abstract"),
  n("industria", "industria", "industry", "f", "work"),
  n("economia", "economia", "economy", "f", "abstract"),
  n("politica", "politica", "politics", "f", "abstract"),
  n("governo", "governo", "government", "m", "abstract"),
  n("stato", "stato", "state", "m", "abstract"),
  n("ministero", "ministero", "ministry", "m", "abstract"),
  n("parlamento", "parlamento", "parliament", "m", "abstract"),
  n("elezione", "elezione", "election", "f", "abstract"),
  n("partito", "partito", "political party", "m", "abstract"),
  n("democrazia", "democrazia", "democracy", "f", "abstract"),
  n("repubblica", "repubblica", "republic", "f", "abstract"),
  n("costituzione", "costituzione", "constitution", "f", "abstract"),
  n("cittadinanza", "cittadinanza", "citizenship", "f", "abstract"),
  n("ambasciatore", "ambasciatore", "ambassador", "m", "person"),
  n("trattato", "trattato", "treaty", "m", "abstract"),
  n("alleanza", "alleanza", "alliance", "f", "abstract"),
  n("recessione", "recessione", "recession", "f", "abstract"),
  n("inflazione", "inflazione", "inflation", "f", "abstract"),
  n("burocrazia", "burocrazia", "bureaucracy", "f", "abstract"),
  n("corruzione", "corruzione", "corruption", "f", "abstract"),
  n("trasparenza", "trasparenza", "transparency", "f", "abstract"),
  n("privacy", "privacy", "privacy", "f", "abstract"),
  n("giuria", "giuria", "jury", "f", "abstract"),
  n("processo", "processo", "trial", "m", "abstract"),
  n("sentenza", "sentenza", "sentence (legal)", "f", "abstract"),
  n("pena", "pena", "punishment", "f", "abstract"),
  n("multa", "multa", "fine", "f", "abstract"),
  n("proibizione", "proibizione", "ban", "f", "abstract"),
  n("limite", "limite", "limit", "m", "abstract"),
  n("eccezione", "eccezione", "exception", "f", "abstract"),
  n("norma", "norma", "norm", "f", "abstract"),
  n("qualita", "qualità", "quality", "f", "abstract"),
  n("quantita", "quantità", "quantity", "f", "abstract"),
  n("misura", "misura", "measure", "f", "abstract"),
  n("peso", "peso", "weight", "m", "abstract"),
  n("altezza", "altezza", "height", "f", "abstract"),
  n("lunghezza", "lunghezza", "length", "f", "abstract"),
  n("larghezza", "larghezza", "width", "f", "abstract"),
  n("profondita", "profondità", "depth", "f", "abstract"),
  n("distanza", "distanza", "distance", "f", "abstract"),
  n("velocita", "velocità", "speed", "f", "abstract"),
  n("potenza", "potenza", "power", "f", "abstract"),
  n("elettricita", "elettricità", "electricity", "f", "abstract"),
  n("petrolio", "petrolio", "oil", "m", "abstract"),
  n("ambiente", "ambiente", "environment", "m", "abstract"),
  n("inquinamento", "inquinamento", "pollution", "m", "abstract"),
  n("riciclaggio", "riciclaggio", "recycling", "m", "abstract"),
  n("sostenibilita", "sostenibilità", "sustainability", "f", "abstract"),
  n("biodiversita", "biodiversità", "biodiversity", "f", "abstract"),
  n("ecosistema", "ecosistema", "ecosystem", "m", "abstract"),
  n("riscaldamento", "riscaldamento", "warming", "m", "abstract"),
  n("siccita", "siccità", "drought", "f", "abstract"),
  n("alluvione", "alluvione", "flood", "f", "abstract"),
  n("terremoto", "terremoto", "earthquake", "m", "abstract"),
  n("vulcano", "vulcano", "volcano", "m", "abstract"),
  n("uragano", "uragano", "hurricane", "m", "abstract"),
  n("startup", "startup", "startup", "f", "work"),
  n("investimento", "investimento", "investment", "m", "work"),
  n("dividendo", "dividendo", "dividend", "m", "work"),
  n("borsa", "borsa", "stock exchange", "f", "work"),
  n("mercato", "mercato_fin", "financial market", "m", "work"),
  n("concorrenza", "concorrenza", "competition", "f", "abstract"),
  n("monopolio", "monopolio", "monopoly", "m", "abstract"),
  n("globalizzazione", "globalizzazione", "globalization", "f", "abstract"),
  n("rivoluzione", "rivoluzione", "revolution", "f", "abstract"),
  n("manifestazione", "manifestazione", "demonstration", "f", "abstract"),
  n("sciopero", "sciopero", "strike", "m", "abstract"),
  n("sindacato", "sindacato", "union", "m", "abstract"),
  n("dirigente", "dirigente", "executive", "m", "person"),
  n("imprenditore", "imprenditore", "entrepreneur", "m", "person"),
  n("investitore", "investitore", "investor", "m", "person"),
  n("azionista", "azionista", "shareholder", "m", "person"),
  n("consulente", "consulente", "consultant", "m", "person"),
  n("analista", "analista", "analyst", "m", "person"),
  n("revisore", "revisore", "auditor", "m", "person"),
  n("contabile", "contabile", "accountant", "m", "person"),
  n("archivio", "archivio", "archive", "m", "work"),
  n("database", "database", "database", "m", "communication"),
  n("server", "server", "server", "m", "communication"),
  n("cloud", "cloud", "cloud", "m", "communication"),
  n("algoritmo", "algoritmo", "algorithm", "m", "abstract"),
  n("intelligenza", "intelligenza", "intelligence", "f", "abstract"),
  n("robot", "robot", "robot", "m", "object"),
  n("automazione", "automazione", "automation", "f", "abstract"),
  n("blockchain", "blockchain", "blockchain", "f", "abstract"),
  n("criptovaluta", "criptovaluta", "cryptocurrency", "f", "abstract"),
  n("marketing", "marketing", "marketing", "m", "work"),
  n("pubblicita", "pubblicità", "advertising", "f", "communication"),
  n("marchio", "marchio", "brand", "m", "work"),
  n("logo", "logo", "logo", "m", "object"),
  n("campagna", "campagna", "campaign", "f", "work"),
  n("target", "target", "target", "m", "work"),
  n("clientela", "clientela", "clientele", "f", "work"),
  n("fidelizzazione", "fidelizzazione", "loyalty", "f", "work"),
  n("reclamo", "reclamo", "complaint", "m", "work"),
  n("rimborso", "rimborso", "refund", "m", "work"),
  n("garanzia", "garanzia", "warranty", "f", "work"),
  n("manutenzione", "manutenzione", "maintenance", "f", "work"),
  n("installazione", "installazione", "installation", "f", "work"),
  n("configurazione", "configurazione", "configuration", "f", "work"),
  n("aggiornamento", "aggiornamento", "update", "m", "work"),
  n("backup", "backup", "backup", "m", "work"),
  n("sicurezza_informatica", "sicurezza informatica", "cybersecurity", "f", "work"),
  ],
  adjectives: [
    adj("politico", "political", "politico", "politica", "politici", "politiche", 5),
    adj("economico", "economic", "economico", "economica", "economici", "economiche", 5),
    adj("globale", "global", "globale", "globale", "globali", "globali", 5),
    adj("nazionale", "national", "nazionale", "nazionale", "nazionali", "nazionali", 5),
    adj("internazionale", "international", "internazionale", "internazionale", "internazionali", "internazionali", 5),
    adj("strategico", "strategic", "strategico", "strategica", "strategici", "strategiche", 5),
  ],
  timeWords: [
    tw("storicamente", "storicamente", "historically", 5),
    tw("globalmente", "globalmente", "globally", 5),
  ],
  connectors: [
    conn("pertanto", "pertanto", "therefore", 5),
    conn("tuttavia", "tuttavia", "however", 5),
    conn("dunque", "dunque", "thus", 5),
    conn("ciononostante", "ciononostante", "nevertheless", 5),
  ],
};
