import type { BulkPack } from "./helpers";
import { adj, conn, n, tw, vAre, vEre, vIre } from "./helpers";

export const BULK_L6: BulkPack = {
  verbs: [
    vAre("argomentare", "argomentare", "argoment", "to argue (reason)", 6),
    vAre("dedurre", "dedurre", "deduc", "to deduce", 6),
    vAre("sintetizzare", "sintetizzare", "sintetizz", "to synthesize", 6),
    vAre("analizzare", "analizzare", "analizz", "to analyze", 6),
    vAre("interpretare", "interpretare", "interpret", "to interpret", 6),
    vAre("ratificare", "ratificare", "ratific", "to ratify", 6),
    vAre("contestare", "contestare", "contest", "to contest", 6),
    vAre("formulare", "formulare", "formul", "to formulate", 6),
    vAre("dimostrare", "dimostrare", "dimostr", "to prove", 6),
  ],
  nouns: [
  n("metafora", "metafora", "metaphor", "f", "abstract"),
  n("allegoria", "allegoria", "allegory", "f", "abstract"),
  n("ironia", "ironia", "irony", "f", "abstract"),
  n("sarcasmo", "sarcasmo", "sarcasm", "m", "abstract"),
  n("paradosso", "paradosso", "paradox", "m", "abstract"),
  n("ambiguita", "ambiguità", "ambiguity", "f", "abstract"),
  n("sottigliezza", "sottigliezza", "nuance", "f", "abstract"),
  n("sfumatura", "sfumatura", "shade/nuance", "f", "abstract"),
  n("analogia", "analogia", "analogy", "f", "abstract"),
  n("sintesi", "sintesi", "synthesis", "f", "abstract"),
  n("tesi", "tesi", "thesis", "f", "abstract"),
  n("antitesi", "antitesi", "antithesis", "f", "abstract"),
  n("ipotesi", "ipotesi", "hypothesis", "f", "abstract"),
  n("metodologia", "metodologia", "methodology", "f", "abstract"),
  n("procedura", "procedura", "procedure", "f", "abstract"),
  n("protocollo", "protocollo", "protocol", "m", "abstract"),
  n("statistica", "statistica", "statistics", "f", "abstract"),
  n("probabilita", "probabilità", "probability", "f", "abstract"),
  n("variabile", "variabile", "variable", "f", "abstract"),
  n("parametro", "parametro", "parameter", "m", "abstract"),
  n("coefficiente", "coefficiente", "coefficient", "m", "abstract"),
  n("equazione", "equazione", "equation", "f", "abstract"),
  n("formula", "formula", "formula", "f", "abstract"),
  n("diagramma", "diagramma", "diagram", "m", "abstract"),
  n("grafico", "grafico", "graph", "m", "abstract"),
  n("tabella", "tabella", "table", "f", "abstract"),
  n("bibliografia", "bibliografia", "bibliography", "f", "abstract"),
  n("citazione", "citazione", "citation", "f", "abstract"),
  n("parafrasi", "parafrasi", "paraphrase", "f", "abstract"),
  n("traduzione", "traduzione", "translation", "f", "abstract"),
  n("interpretazione", "interpretazione", "interpretation", "f", "abstract"),
  n("critica", "critica", "criticism", "f", "abstract"),
  n("recensione", "recensione", "review", "f", "abstract"),
  n("saggio", "saggio", "essay", "m", "abstract"),
  n("editoriale", "editoriale", "editorial", "m", "abstract"),
  n("didascalia", "didascalia", "caption", "f", "abstract"),
  n("prefazione", "prefazione", "preface", "f", "abstract"),
  n("epilogo", "epilogo", "epilogue", "m", "abstract"),
  n("prologo", "prologo", "prologue", "m", "abstract"),
  n("capitolo", "capitolo", "chapter", "m", "abstract"),
  n("paragrafo", "paragrafo", "paragraph", "m", "abstract"),
  n("vocabolo", "vocabolo", "word", "m", "abstract"),
  n("termine", "termine", "term", "m", "abstract"),
  n("definizione", "definizione", "definition", "f", "abstract"),
  n("concetto", "concetto", "concept", "m", "abstract"),
  n("nozione", "nozione", "notion", "f", "abstract"),
  n("paradigma", "paradigma", "paradigm", "m", "abstract"),
  n("retorica", "retorica", "rhetoric", "f", "abstract"),
  n("eloquenza", "eloquenza", "eloquence", "f", "abstract"),
  n("argomentazione", "argomentazione", "argumentation", "f", "abstract"),
  n("dialettica", "dialettica", "dialectic", "f", "abstract"),
  n("controversia", "controversia", "controversy", "f", "abstract"),
  n("polemica", "polemica", "polemic", "f", "abstract"),
  n("dibattito", "dibattito", "debate", "m", "abstract"),
  n("consenso", "consenso", "consensus", "m", "abstract"),
  n("dissenso", "dissenso", "dissent", "m", "abstract"),
  n("compromesso", "compromesso", "compromise", "m", "abstract"),
  n("mediazione", "mediazione", "mediation", "f", "abstract"),
  n("arbitrato", "arbitrato", "arbitration", "m", "abstract"),
  n("litigio", "litigio", "lawsuit", "m", "abstract"),
  n("querela", "querela", "complaint", "f", "abstract"),
  n("testimonianza", "testimonianza", "testimony", "f", "abstract"),
  n("prova", "prova", "evidence", "f", "abstract"),
  n("alibi", "alibi", "alibi", "m", "abstract"),
  n("verdetto", "verdetto", "verdict", "m", "abstract"),
  n("appello", "appello", "appeal", "m", "abstract"),
  n("giurisprudenza", "giurisprudenza", "jurisprudence", "f", "abstract"),
  n("codice", "codice", "code", "m", "abstract"),
  n("emendamento", "emendamento", "amendment", "m", "abstract"),
  n("referendum", "referendum", "referendum", "m", "abstract"),
  n("plebiscito", "plebiscito", "plebiscite", "m", "abstract"),
  n("coalizione", "coalizione", "coalition", "f", "abstract"),
  n("opposizione", "opposizione", "opposition", "f", "abstract"),
  n("maggioranza", "maggioranza", "majority", "f", "abstract"),
  n("minoranza", "minoranza", "minority", "f", "abstract"),
  n("dittatura", "dittatura", "dictatorship", "f", "abstract"),
  n("totalitarismo", "totalitarismo", "totalitarianism", "m", "abstract"),
  n("liberalismo", "liberalismo", "liberalism", "m", "abstract"),
  n("conservatorismo", "conservatorismo", "conservatism", "m", "abstract"),
  n("socialismo", "socialismo", "socialism", "m", "abstract"),
  n("comunismo", "comunismo", "communism", "m", "abstract"),
  n("capitalismo", "capitalismo", "capitalism", "m", "abstract"),
  n("privatizzazione", "privatizzazione", "privatization", "f", "abstract"),
  n("nazionalizzazione", "nazionalizzazione", "nationalization", "f", "abstract"),
  n("oligopolio", "oligopolio", "oligopoly", "m", "abstract"),
  n("derivato", "derivato", "derivative", "m", "work"),
  n("hedge", "hedge fund", "hedge fund", "m", "work"),
  n("leva", "leva finanziaria", "leverage", "f", "work"),
  n("liquidita", "liquidità", "liquidity", "f", "work"),
  n("volatilita", "volatilità", "volatility", "f", "work"),
  n("benchmark", "benchmark", "benchmark", "m", "work"),
  n("portafoglio", "portafoglio fin", "portfolio", "m", "work"),
  n("diversificazione", "diversificazione", "diversification", "f", "work"),
  n("rendimento", "rendimento", "yield", "m", "work"),
  n("ammortamento", "ammortamento", "amortization", "m", "work"),
  n("bilancio", "bilancio", "balance sheet", "m", "work"),
  n("patrimonio", "patrimonio", "equity", "m", "work"),
  n("passivo", "passivo", "liability", "m", "work"),
  n("attivo", "attivo", "asset", "m", "work"),
  n("capitale", "capitale", "capital", "m", "work"),
  n("interesse", "interesse fin", "interest (finance)", "m", "work"),
  n("tasso", "tasso", "rate", "m", "work"),
  n("spread", "spread", "spread", "m", "work"),
  n("rating", "rating", "rating", "m", "work"),
  n("downgrade", "downgrade", "downgrade", "m", "work"),
  n("default", "default", "default", "m", "work"),
  n("ristrutturazione", "ristrutturazione", "restructuring", "f", "work"),
  n("fallimento", "fallimento leg", "bankruptcy", "m", "work"),
  n("fusione", "fusione", "merger", "f", "work"),
  n("acquisizione", "acquisizione", "acquisition", "f", "work"),
  n("due_diligence", "due diligence", "due diligence", "f", "work"),
  n("stakeholder", "stakeholder", "stakeholder", "m", "work"),
  n("governance", "governance", "governance", "f", "work"),
  n("compliance", "compliance", "compliance", "f", "work"),
  n("audit", "audit", "audit", "m", "work"),
  n("whistleblower", "whistleblower", "whistleblower", "m", "person"),
  n("lobby", "lobby", "lobby", "f", "abstract"),
  n("corporativismo", "corporativismo", "corporatism", "m", "abstract"),
  n("autoritarismo", "autoritarismo", "authoritarianism", "m", "abstract"),
  n("nazionalismo", "nazionalismo", "nationalism", "m", "abstract"),
  n("populismo", "populismo", "populism", "m", "abstract"),
  n("federalismo", "federalismo", "federalism", "m", "abstract"),
  n("separatismo", "separatismo", "separatism", "m", "abstract"),
  n("colonialismo", "colonialismo", "colonialism", "m", "abstract"),
  n("imperialismo", "imperialismo", "imperialism", "m", "abstract"),
  n("postmodernismo", "postmodernismo", "postmodernism", "m", "abstract"),
  n("esistenzialismo", "esistenzialismo", "existentialism", "m", "abstract"),
  n("stoicismo", "stoicismo", "stoicism", "m", "abstract"),
  n("epistemologia", "epistemologia", "epistemology", "f", "abstract"),
  n("ontologia", "ontologia", "ontology", "f", "abstract"),
  n("etica", "etica", "ethics", "f", "abstract"),
  n("estetica", "estetica", "aesthetics", "f", "abstract"),
  n("fenomenologia", "fenomenologia", "phenomenology", "f", "abstract"),
  n("ermeneutica", "ermeneutica", "hermeneutics", "f", "abstract"),
  n("decostruzione", "decostruzione", "deconstruction", "f", "abstract"),
  n("intertestualita", "intertestualità", "intertextuality", "f", "abstract"),
  n("sincretismo", "sincretismo", "syncretism", "m", "abstract"),
  n("iconografia", "iconografia", "iconography", "f", "abstract"),
  n("prospettiva", "prospettiva", "perspective", "f", "abstract"),
  n("prospettiva_lineare", "prospettiva lineare", "linear perspective", "f", "abstract"),
  ],
  adjectives: [
    adj("ambiguo", "ambiguous", "ambiguo", "ambigua", "ambigui", "ambigue", 6),
    adj("filosofico", "philosophical", "filosofico", "filosofica", "filosofici", "filosofiche", 6),
    adj("accademico", "academic", "accademico", "accademica", "accademici", "accademiche", 6),
    adj("retorico", "rhetorical", "retorico", "retorica", "retorici", "retoriche", 6),
    adj("giuridico", "legal", "giuridico", "giuridica", "giuridici", "giuridiche", 6),
  ],
  timeWords: [
    tw("filologicamente", "filologicamente", "philologically", 6),
  ],
  connectors: [
    conn("ossia", "ossia", "that is to say", 6),
    conn("eppure", "eppure", "and yet", 6),
    conn("nondimeno", "nondimeno", "nonetheless", 6),
    conn("altrimenti_detto", "detto altrimenti", "in other words", 6),
  ],
};
