import type {
  Adjective,
  Connector,
  Noun,
  Pronoun,
  TimeWord,
  Verb,
} from "@/lib/italian-coach/types";

export const pronouns: Pronoun[] = [
  { id: "io", word: "io", english: "I", person: "io", plural: false },
  { id: "tu", word: "tu", english: "you", person: "tu", plural: false },
  { id: "lui", word: "lui", english: "he", person: "lui_lei", plural: false },
  { id: "lei", word: "lei", english: "she", person: "lui_lei", plural: false },
  { id: "noi", word: "noi", english: "we", person: "noi", plural: true },
  { id: "voi", word: "voi", english: "you all", person: "voi", plural: true },
  { id: "loro", word: "loro", english: "they", person: "loro", plural: true },
];

export const verbs: Verb[] = [
  {
    id: "essere",
    infinitive: "essere",
    english: "to be",
    present: { io: "sono", tu: "sei", lui_lei: "è", noi: "siamo", voi: "siete", loro: "sono" },
  },
  {
    id: "avere",
    infinitive: "avere",
    english: "to have",
    present: { io: "ho", tu: "hai", lui_lei: "ha", noi: "abbiamo", voi: "avete", loro: "hanno" },
  },
  {
    id: "volere",
    infinitive: "volere",
    english: "to want",
    present: { io: "voglio", tu: "vuoi", lui_lei: "vuole", noi: "vogliamo", voi: "volete", loro: "vogliono" },
  },
  {
    id: "potere",
    infinitive: "potere",
    english: "to be able / can",
    present: { io: "posso", tu: "puoi", lui_lei: "può", noi: "possiamo", voi: "potete", loro: "possono" },
  },
  {
    id: "dovere",
    infinitive: "dovere",
    english: "to have to / must",
    present: { io: "devo", tu: "devi", lui_lei: "deve", noi: "dobbiamo", voi: "dovete", loro: "devono" },
  },
  {
    id: "sapere",
    infinitive: "sapere",
    english: "to know",
    present: { io: "so", tu: "sai", lui_lei: "sa", noi: "sappiamo", voi: "sapete", loro: "sanno" },
  },
  {
    id: "andare",
    infinitive: "andare",
    english: "to go",
    present: { io: "vado", tu: "vai", lui_lei: "va", noi: "andiamo", voi: "andate", loro: "vanno" },
  },
  {
    id: "venire",
    infinitive: "venire",
    english: "to come",
    present: { io: "vengo", tu: "vieni", lui_lei: "viene", noi: "veniamo", voi: "venite", loro: "vengono" },
  },
  {
    id: "fare",
    infinitive: "fare",
    english: "to do / make",
    present: { io: "faccio", tu: "fai", lui_lei: "fa", noi: "facciamo", voi: "fate", loro: "fanno" },
  },
  {
    id: "dire",
    infinitive: "dire",
    english: "to say",
    present: { io: "dico", tu: "dici", lui_lei: "dice", noi: "diciamo", voi: "dite", loro: "dicono" },
  },
  {
    id: "vedere",
    infinitive: "vedere",
    english: "to see",
    present: { io: "vedo", tu: "vedi", lui_lei: "vede", noi: "vediamo", voi: "vedete", loro: "vedono" },
  },
  {
    id: "mangiare",
    infinitive: "mangiare",
    english: "to eat",
    present: { io: "mangio", tu: "mangi", lui_lei: "mangia", noi: "mangiamo", voi: "mangiate", loro: "mangiano" },
  },
  {
    id: "bere",
    infinitive: "bere",
    english: "to drink",
    present: { io: "bevo", tu: "bevi", lui_lei: "beve", noi: "beviamo", voi: "bevete", loro: "bevono" },
  },
  {
    id: "parlare",
    infinitive: "parlare",
    english: "to speak",
    present: { io: "parlo", tu: "parli", lui_lei: "parla", noi: "parliamo", voi: "parlate", loro: "parlano" },
  },
  {
    id: "leggere",
    infinitive: "leggere",
    english: "to read",
    present: { io: "leggo", tu: "leggi", lui_lei: "legge", noi: "leggiamo", voi: "leggete", loro: "leggono" },
  },
  {
    id: "scrivere",
    infinitive: "scrivere",
    english: "to write",
    present: { io: "scrivo", tu: "scrivi", lui_lei: "scrive", noi: "scriviamo", voi: "scrivete", loro: "scrivono" },
  },
  {
    id: "dormire",
    infinitive: "dormire",
    english: "to sleep",
    present: { io: "dormo", tu: "dormi", lui_lei: "dorme", noi: "dormiamo", voi: "dormite", loro: "dormono" },
  },
  {
    id: "lavorare",
    infinitive: "lavorare",
    english: "to work",
    present: { io: "lavoro", tu: "lavori", lui_lei: "lavora", noi: "lavoriamo", voi: "lavorate", loro: "lavorano" },
  },
  {
    id: "studiare",
    infinitive: "studiare",
    english: "to study",
    present: { io: "studio", tu: "studi", lui_lei: "studia", noi: "studiamo", voi: "studiate", loro: "studiano" },
  },
  {
    id: "comprare",
    infinitive: "comprare",
    english: "to buy",
    present: { io: "compro", tu: "compri", lui_lei: "compra", noi: "compriamo", voi: "comprate", loro: "comprano" },
  },
  {
    id: "vivere",
    infinitive: "vivere",
    english: "to live",
    present: { io: "vivo", tu: "vivi", lui_lei: "vive", noi: "viviamo", voi: "vivete", loro: "vivono" },
  },
  {
    id: "amare",
    infinitive: "amare",
    english: "to love",
    present: { io: "amo", tu: "ami", lui_lei: "ama", noi: "amiamo", voi: "amate", loro: "amano" },
  },
  {
    id: "capire",
    infinitive: "capire",
    english: "to understand",
    present: { io: "capisco", tu: "capisci", lui_lei: "capisce", noi: "capiamo", voi: "capite", loro: "capiscono" },
  },
  {
    id: "pensare",
    infinitive: "pensare",
    english: "to think",
    present: { io: "penso", tu: "pensi", lui_lei: "pensa", noi: "pensiamo", voi: "pensate", loro: "pensano" },
  },
];

export const nouns: Noun[] = [
  // Food & drink
  { id: "te", singular: "tè", plural: "tè", english: "tea", gender: "m" },
  { id: "caffe", singular: "caffè", plural: "caffè", english: "coffee", gender: "m" },
  { id: "acqua", singular: "acqua", plural: "acque", english: "water", gender: "f" },
  { id: "pizza", singular: "pizza", plural: "pizze", english: "pizza", gender: "f" },
  { id: "pane", singular: "pane", plural: "pani", english: "bread", gender: "m" },
  { id: "vino", singular: "vino", plural: "vini", english: "wine", gender: "m" },
  { id: "latte", singular: "latte", plural: "latti", english: "milk", gender: "m" },
  { id: "pasta", singular: "pasta", plural: "paste", english: "pasta", gender: "f" },
  { id: "mela", singular: "mela", plural: "mele", english: "apple", gender: "f" },
  { id: "formaggio", singular: "formaggio", plural: "formaggi", english: "cheese", gender: "m" },
  { id: "zucchero", singular: "zucchero", plural: "zuccheri", english: "sugar", gender: "m", articleSingular: "lo" },
  // Places
  { id: "casa", singular: "casa", plural: "case", english: "house", gender: "f" },
  { id: "scuola", singular: "scuola", plural: "scuole", english: "school", gender: "f" },
  { id: "citta", singular: "città", plural: "città", english: "city", gender: "f" },
  { id: "piazza", singular: "piazza", plural: "piazze", english: "square", gender: "f" },
  { id: "ristorante", singular: "ristorante", plural: "ristoranti", english: "restaurant", gender: "m" },
  { id: "ufficio", singular: "ufficio", plural: "uffici", english: "office", gender: "m" },
  { id: "mercato", singular: "mercato", plural: "mercati", english: "market", gender: "m" },
  { id: "giardino", singular: "giardino", plural: "giardini", english: "garden", gender: "m" },
  { id: "strada", singular: "strada", plural: "strade", english: "street", gender: "f" },
  { id: "stazione", singular: "stazione", plural: "stazioni", english: "station", gender: "f" },
  // People
  { id: "amico", singular: "amico", plural: "amici", english: "friend (m)", gender: "m" },
  { id: "amica", singular: "amica", plural: "amiche", english: "friend (f)", gender: "f" },
  { id: "donna", singular: "donna", plural: "donne", english: "woman", gender: "f" },
  { id: "uomo", singular: "uomo", plural: "uomini", english: "man", gender: "m" },
  { id: "ragazzo", singular: "ragazzo", plural: "ragazzi", english: "boy", gender: "m" },
  { id: "ragazza", singular: "ragazza", plural: "ragazze", english: "girl", gender: "f" },
  { id: "bambino", singular: "bambino", plural: "bambini", english: "child (m)", gender: "m" },
  { id: "famiglia", singular: "famiglia", plural: "famiglie", english: "family", gender: "f" },
  { id: "studente", singular: "studente", plural: "studenti", english: "student", gender: "m", articleSingular: "lo" },
  // Objects
  { id: "libro", singular: "libro", plural: "libri", english: "book", gender: "m" },
  { id: "tavolo", singular: "tavolo", plural: "tavoli", english: "table", gender: "m" },
  { id: "sedia", singular: "sedia", plural: "sedie", english: "chair", gender: "f" },
  { id: "macchina", singular: "macchina", plural: "macchine", english: "car", gender: "f" },
  { id: "telefono", singular: "telefono", plural: "telefoni", english: "phone", gender: "m" },
  { id: "finestra", singular: "finestra", plural: "finestre", english: "window", gender: "f" },
  { id: "porta", singular: "porta", plural: "porte", english: "door", gender: "f" },
  // Time & Abstract
  { id: "giorno", singular: "giorno", plural: "giorni", english: "day", gender: "m" },
  { id: "notte", singular: "notte", plural: "notti", english: "night", gender: "f" },
  { id: "mattina", singular: "mattina", plural: "mattine", english: "morning", gender: "f" },
  { id: "sera", singular: "sera", plural: "sere", english: "evening", gender: "f" },
  { id: "anno", singular: "anno", plural: "anni", english: "year", gender: "m" },
  { id: "tempo", singular: "tempo", plural: "tempi", english: "time / weather", gender: "m" },
  { id: "vita", singular: "vita", plural: "vite", english: "life", gender: "f" },
  { id: "lavoro", singular: "lavoro", plural: "lavori", english: "work / job", gender: "m" },
  { id: "amore", singular: "amore", plural: "amori", english: "love", gender: "m" },
  { id: "parola", singular: "parola", plural: "parole", english: "word", gender: "f" },
];

export const adjectives: Adjective[] = [
  { id: "bello", english: "beautiful", m_sg: "bello", f_sg: "bella", m_pl: "belli", f_pl: "belle" },
  { id: "brutto", english: "ugly", m_sg: "brutto", f_sg: "brutta", m_pl: "brutti", f_pl: "brutte" },
  { id: "grande", english: "big", m_sg: "grande", f_sg: "grande", m_pl: "grandi", f_pl: "grandi" },
  { id: "piccolo", english: "small", m_sg: "piccolo", f_sg: "piccola", m_pl: "piccoli", f_pl: "piccole" },
  { id: "buono", english: "good", m_sg: "buono", f_sg: "buona", m_pl: "buoni", f_pl: "buone" },
  { id: "cattivo", english: "bad", m_sg: "cattivo", f_sg: "cattiva", m_pl: "cattivi", f_pl: "cattive" },
  { id: "alto", english: "tall", m_sg: "alto", f_sg: "alta", m_pl: "alti", f_pl: "alte" },
  { id: "basso", english: "short", m_sg: "basso", f_sg: "bassa", m_pl: "bassi", f_pl: "basse" },
  { id: "vecchio", english: "old", m_sg: "vecchio", f_sg: "vecchia", m_pl: "vecchi", f_pl: "vecchie" },
  { id: "nuovo", english: "new", m_sg: "nuovo", f_sg: "nuova", m_pl: "nuovi", f_pl: "nuove" },
  { id: "caldo", english: "hot", m_sg: "caldo", f_sg: "calda", m_pl: "caldi", f_pl: "calde" },
  { id: "freddo", english: "cold", m_sg: "freddo", f_sg: "fredda", m_pl: "freddi", f_pl: "fredde" },
  { id: "felice", english: "happy", m_sg: "felice", f_sg: "felice", m_pl: "felici", f_pl: "felici" },
  { id: "triste", english: "sad", m_sg: "triste", f_sg: "triste", m_pl: "tristi", f_pl: "tristi" },
  { id: "importante", english: "important", m_sg: "importante", f_sg: "importante", m_pl: "importanti", f_pl: "importanti" },
];

export const timeWords: TimeWord[] = [
  { id: "oggi", word: "oggi", english: "today" },
  { id: "domani", word: "domani", english: "tomorrow" },
  { id: "ieri", word: "ieri", english: "yesterday" },
  { id: "ora", word: "ora", english: "now" },
  { id: "sempre", word: "sempre", english: "always" },
  { id: "mai", word: "mai", english: "never" },
  { id: "spesso", word: "spesso", english: "often" },
  { id: "presto", word: "presto", english: "early / soon" },
  { id: "tardi", word: "tardi", english: "late" },
  { id: "molto", word: "molto", english: "very / a lot" },
];

export const connectors: Connector[] = [
  { id: "e", word: "e", english: "and" },
  { id: "ma", word: "ma", english: "but" },
  { id: "o", word: "o", english: "or" },
  { id: "perche", word: "perché", english: "because" },
  { id: "con", word: "con", english: "with" },
  { id: "senza", word: "senza", english: "without" },
  { id: "per", word: "per", english: "for" },
  { id: "anche", word: "anche", english: "also" },
  { id: "se", word: "se", english: "if" },
  { id: "quando", word: "quando", english: "when" },
];
