import type { CompanyRecord } from "./types";

export const COMPANY_REGISTRY: CompanyRecord[] = [
  {
    name: "Razorpay",
    slug: "razorpay",
    careersPageUrl: "https://jobs.lever.co/razorpay",
    atsPlatform: "lever",
    atsSlug: "razorpay",
    sector: "Fintech",
    hqCity: "Bengaluru",
    hqCountry: "India",
    indiaOffices: ["Bengaluru"],
    fundingStatus: "Series F",
    pmMaturityScore: 8,
    brandValueScore: 9,
    stabilityScore: 8,
  },
  {
    name: "CRED",
    slug: "cred",
    careersPageUrl: "https://boards.greenhouse.io/embed/job_board?for=cred",
    atsPlatform: "greenhouse",
    atsSlug: "cred",
    sector: "Fintech",
    hqCity: "Bengaluru",
    hqCountry: "India",
    indiaOffices: ["Bengaluru"],
    fundingStatus: "Series F",
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 7,
  },
  {
    name: "Zepto",
    slug: "zepto",
    careersPageUrl: "https://jobs.lever.co/zepto",
    atsPlatform: "lever",
    atsSlug: "zepto",
    sector: "Consumer / Quick Commerce",
    hqCity: "Mumbai",
    hqCountry: "India",
    indiaOffices: ["Mumbai", "Bengaluru"],
    fundingStatus: "Series F",
    pmMaturityScore: 7,
    brandValueScore: 8,
    stabilityScore: 7,
  },
  {
    name: "Swiggy",
    slug: "swiggy",
    careersPageUrl: "https://jobs.lever.co/swiggy",
    atsPlatform: "lever",
    atsSlug: "swiggy",
    sector: "Consumer / Food Tech",
    hqCity: "Bengaluru",
    hqCountry: "India",
    indiaOffices: ["Bengaluru"],
    fundingStatus: "Public (BSE/NSE)",
    isPublic: true,
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 8,
  },
  {
    name: "Meesho",
    slug: "meesho",
    careersPageUrl: "https://boards.greenhouse.io/embed/job_board?for=meesho",
    atsPlatform: "greenhouse",
    atsSlug: "meesho",
    sector: "Consumer / E-commerce",
    hqCity: "Bengaluru",
    hqCountry: "India",
    indiaOffices: ["Bengaluru"],
    fundingStatus: "Series F",
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 8,
  },
  {
    name: "Google",
    slug: "google",
    careersPageUrl: "https://careers.google.com/jobs/results/?location=India",
    atsPlatform: "direct",
    sector: "Big Tech",
    hqCity: "Mountain View",
    hqCountry: "US",
    indiaOffices: ["Bengaluru", "Hyderabad", "Mumbai", "Gurgaon"],
    isPublic: true,
    pmMaturityScore: 10,
    brandValueScore: 10,
    stabilityScore: 10,
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    careersPageUrl: "https://careers.microsoft.com/us/en/search-results?location=India",
    atsPlatform: "direct",
    sector: "Big Tech",
    hqCity: "Redmond",
    hqCountry: "US",
    indiaOffices: ["Bengaluru", "Hyderabad", "Noida"],
    isPublic: true,
    pmMaturityScore: 10,
    brandValueScore: 10,
    stabilityScore: 10,
  },
];

export function getCompanyRegistry(activeOnly = true): CompanyRecord[] {
  if (!activeOnly) return COMPANY_REGISTRY;
  return COMPANY_REGISTRY.filter((company) => (company.scrapeErrorCount ?? 0) <= 5);
}
