import type { CompanyRecord } from "./types";

type Region = "IN" | "US" | "EU" | "GLOBAL";

function gh(
  slug: string,
  name: string,
  sector: string,
  region: Region = "US",
): CompanyRecord {
  const india = region === "IN";
  return {
    name,
    slug: slug.replace(/_/g, "-"),
    careersPageUrl: `https://boards.greenhouse.io/${slug}`,
    atsPlatform: "greenhouse",
    atsSlug: slug,
    sector,
    hqCity: india ? "Bengaluru" : "San Francisco",
    hqCountry: india ? "India" : "US",
    indiaOffices: india ? ["Bengaluru", "Hyderabad"] : ["Bengaluru", "Remote India"],
    pmMaturityScore: 7,
    brandValueScore: 7,
    stabilityScore: 7,
  };
}

function lv(
  leverSlug: string,
  name: string,
  sector: string,
  region: Region = "IN",
  /** Canonical registry slug (defaults to leverSlug). Use when API slug differs, e.g. zeptonow → zepto. */
  registrySlug?: string,
): CompanyRecord {
  const india = region === "IN";
  const slug = (registrySlug ?? leverSlug).replace(/_/g, "-");
  return {
    name,
    slug,
    careersPageUrl: `https://jobs.lever.co/${leverSlug}`,
    atsPlatform: "lever",
    atsSlug: leverSlug,
    sector,
    hqCity: india ? "Bengaluru" : "San Francisco",
    hqCountry: india ? "India" : "US",
    indiaOffices: india ? ["Bengaluru"] : ["Remote India"],
    pmMaturityScore: 7,
    brandValueScore: 7,
    stabilityScore: 7,
  };
}

function ash(slug: string, name: string, sector: string): CompanyRecord {
  return {
    name,
    slug: slug.replace(/_/g, "-"),
    careersPageUrl: `https://jobs.ashbyhq.com/${slug}`,
    atsPlatform: "ashby",
    atsSlug: slug,
    sector,
    hqCity: "San Francisco",
    hqCountry: "US",
    indiaOffices: ["Remote India", "Bengaluru"],
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 8,
  };
}

function sr(slug: string, name: string): CompanyRecord {
  return {
    name,
    slug: slug.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, ""),
    careersPageUrl: `https://careers.smartrecruiters.com/${encodeURIComponent(name)}`,
    atsPlatform: "smartrecruiters",
    atsSlug: slug,
    sector: "Enterprise",
    hqCity: "Global",
    hqCountry: "Various",
    indiaOffices: ["Bengaluru", "Hyderabad"],
    pmMaturityScore: 7,
    brandValueScore: 8,
    stabilityScore: 8,
  };
}

function wd(name: string, slug: string, workdayUrl: string): CompanyRecord {
  return {
    name,
    slug,
    careersPageUrl: workdayUrl,
    atsPlatform: "workday",
    workdayUrl,
    sector: "Enterprise",
    hqCity: "Various",
    hqCountry: "Various",
    indiaOffices: ["Bengaluru", "Hyderabad", "Pune"],
    pmMaturityScore: 7,
    brandValueScore: 7,
    stabilityScore: 7,
  };
}

function dr(name: string, slug: string, url: string, sector: string, region: Region = "IN"): CompanyRecord {
  const india = region === "IN";
  return {
    name,
    slug,
    careersPageUrl: url,
    atsPlatform: "direct",
    sector,
    hqCity: india ? "Bengaluru" : "Global",
    hqCountry: india ? "India" : "US",
    indiaOffices: india ? ["Bengaluru"] : ["Remote India"],
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 7,
  };
}

/** India + global Greenhouse boards (slug must match boards-api path). */
const GREENHOUSE: CompanyRecord[] = [
  gh("freshworks", "Freshworks", "SaaS", "IN"),
  gh("browserstack", "BrowserStack", "SaaS", "IN"),
  gh("meesho", "Meesho", "Consumer", "IN"),
  gh("groww", "Groww", "Fintech", "IN"),
  gh("chargebee", "Chargebee", "SaaS", "IN"),
  gh("acko", "Acko", "Fintech", "IN"),
  gh("ixigo", "Ixigo", "Consumer", "IN"),
  gh("cars24", "Cars24", "Consumer", "IN"),
  gh("urbancompany", "Urban Company", "Consumer", "IN"),
  gh("postman", "Postman", "SaaS", "IN"),
  gh("clevertap", "CleverTap", "SaaS", "IN"),
  gh("sprinklr", "Sprinklr", "SaaS", "IN"),
  gh("moengage", "MoEngage", "SaaS", "IN"),
  {
    name: "CRED",
    slug: "cred",
    careersPageUrl: "https://boards.greenhouse.io/dreamplug",
    atsPlatform: "greenhouse",
    atsSlug: "dreamplug",
    sector: "Fintech",
    hqCity: "Bengaluru",
    hqCountry: "India",
    indiaOffices: ["Bengaluru"],
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 7,
  },
  gh("setu", "Setu", "Fintech", "IN"),
  gh("smallcase", "Smallcase", "Fintech", "IN"),
  gh("niyo", "Niyo", "Fintech", "IN"),
  gh("epifi", "Fi Money", "Fintech", "IN"),
  gh("jupiter", "Jupiter Money", "Fintech", "IN"),
  gh("acceldata", "Acceldata", "Infra", "IN"),
  gh("leadsquared", "LeadSquared", "SaaS", "IN"),
  gh("hasura", "Hasura", "Infra", "IN"),
  gh("tooljet", "ToolJet", "SaaS", "IN"),
  gh("appsmith", "Appsmith", "SaaS", "IN"),
  gh("rudderstack", "RudderStack", "SaaS", "IN"),
  gh("clarisights", "Clarisights", "SaaS", "IN"),
  gh("kapture", "Kapture CX", "SaaS", "IN"),
  gh("cashfree", "Cashfree", "Fintech", "IN"),
  gh("signzy", "Signzy", "Fintech", "IN"),
  gh("atlassian", "Atlassian", "BigTech", "US"),
  gh("uber", "Uber", "BigTech", "US"),
  gh("linkedin", "LinkedIn", "BigTech", "US"),
  gh("salesforce", "Salesforce", "BigTech", "US"),
  gh("stripe", "Stripe", "Fintech", "US"),
  gh("notion", "Notion", "SaaS", "US"),
  gh("figma", "Figma", "SaaS", "US"),
  gh("vercel", "Vercel", "SaaS", "US"),
  gh("anthropic", "Anthropic", "AI", "US"),
  gh("cohere", "Cohere", "AI", "US"),
  {
    name: "Scale AI",
    slug: "scale-ai",
    careersPageUrl: "https://boards.greenhouse.io/scaleai",
    atsPlatform: "greenhouse",
    atsSlug: "scaleai",
    sector: "AI",
    hqCity: "San Francisco",
    hqCountry: "US",
    indiaOffices: ["Remote India"],
    pmMaturityScore: 8,
    brandValueScore: 9,
    stabilityScore: 7,
  },
  gh("coinbase", "Coinbase", "Fintech", "US"),
  gh("airbnb", "Airbnb", "Consumer", "US"),
  gh("dropbox", "Dropbox", "SaaS", "US"),
  gh("twilio", "Twilio", "SaaS", "US"),
  gh("segment", "Segment", "SaaS", "US"),
  gh("brex", "Brex", "Fintech", "US"),
  gh("rippling", "Rippling", "SaaS", "US"),
  gh("lattice", "Lattice", "SaaS", "US"),
  gh("amplitude", "Amplitude", "SaaS", "US"),
  gh("mixpanel", "Mixpanel", "SaaS", "US"),
  gh("intercom", "Intercom", "SaaS", "US"),
  gh("zendesk", "Zendesk", "SaaS", "US"),
  gh("hubspot", "HubSpot", "SaaS", "US"),
  gh("asana", "Asana", "SaaS", "US"),
  gh("gitlab", "GitLab", "SaaS", "US"),
  gh("hashicorp", "HashiCorp", "Infra", "US"),
  gh("mongodb", "MongoDB", "Infra", "US"),
  gh("datadog", "Datadog", "SaaS", "US"),
  gh("elastic", "Elastic", "Infra", "US"),
  gh("confluent", "Confluent", "Infra", "US"),
  gh("benchling", "Benchling", "SaaS", "US"),
  gh("carta", "Carta", "Fintech", "US"),
  gh("chime", "Chime", "Fintech", "US"),
  gh("plaid", "Plaid", "Fintech", "US"),
  gh("marqeta", "Marqeta", "Fintech", "US"),
  gh("affirm", "Affirm", "Fintech", "US"),
  gh("checkr", "Checkr", "SaaS", "US"),
  gh("gusto", "Gusto", "SaaS", "US"),
  gh("toast", "Toast", "Consumer", "US"),
  gh("procore", "Procore", "SaaS", "US"),
  gh("samsara", "Samsara", "SaaS", "US"),
  gh("verkada", "Verkada", "SaaS", "US"),
  {
    name: "Wise",
    slug: "wise",
    careersPageUrl: "https://boards.greenhouse.io/wiseuk",
    atsPlatform: "greenhouse",
    atsSlug: "wiseuk",
    sector: "Fintech",
    hqCity: "London",
    hqCountry: "UK",
    indiaOffices: ["Bengaluru"],
    pmMaturityScore: 8,
    brandValueScore: 8,
    stabilityScore: 8,
  },
  gh("revolut", "Revolut", "Fintech", "EU"),
  gh("monzo", "Monzo", "Fintech", "EU"),
  gh("gocardless", "GoCardless", "Fintech", "EU"),
  gh("checkout", "Checkout.com", "Fintech", "EU"),
  gh("sumup", "SumUp", "Fintech", "EU"),
  gh("klarna", "Klarna", "Fintech", "EU"),
  gh("adyen", "Adyen", "Fintech", "EU"),
  gh("huggingface", "Hugging Face", "AI", "US"),
  gh("mistral", "Mistral AI", "AI", "EU"),
  gh("together", "Together AI", "AI", "US"),
  gh("anyscale", "Anyscale", "AI", "US"),
  gh("wandb", "Weights & Biases", "AI", "US"),
  gh("landingai", "Landing AI", "AI", "US"),
  gh("labelbox", "Labelbox", "AI", "US"),
  gh("snorkel", "Snorkel AI", "AI", "US"),
  gh("meta", "Meta", "BigTech", "US"),
];

const LEVER: CompanyRecord[] = [
  lv("razorpay", "Razorpay", "Fintech", "IN"),
  lv("swiggy", "Swiggy", "Consumer", "IN"),
  lv("zeptonow", "Zepto", "Consumer", "IN", "zepto"),
  lv("spinny", "Spinny", "Consumer", "IN"),
  lv("purplle", "Purplle", "Consumer", "IN"),
  lv("mpl", "MPL", "Consumer", "IN"),
  lv("sliceit", "Slice", "Fintech", "IN", "slice"),
  lv("openfinancial", "Open Financial", "Fintech", "IN", "open-financial"),
  lv("dunzo", "Dunzo", "Consumer", "IN"),
  lv("milkbasket", "Milkbasket", "Consumer", "IN"),
  lv("shadowfax", "Shadowfax", "Logistics", "IN"),
  lv("delhivery", "Delhivery", "Logistics", "IN"),
  lv("loadshare", "LoadShare", "Logistics", "IN"),
  lv("porter", "Porter", "Logistics", "IN"),
  lv("rapido", "Rapido", "Consumer", "IN"),
  lv("yulu", "Yulu", "Consumer", "IN"),
  lv("bounce", "Bounce", "Consumer", "IN"),
  lv("vedantu", "Vedantu", "Edtech", "IN"),
  lv("physicswallah", "Physics Wallah", "Edtech", "IN"),
  lv("unacademy", "Unacademy", "Edtech", "IN"),
  lv("classplus", "Classplus", "Edtech", "IN"),
  lv("leadschool", "Lead School", "Edtech", "IN"),
  lv("eruditus", "Eruditus", "Edtech", "IN"),
  lv("emeritus", "Emeritus", "Edtech", "IN"),
  lv("upgrad", "upGrad", "Edtech", "IN"),
  lv("masaischool", "Masai School", "Edtech", "IN"),
  lv("scaler", "Scaler", "Edtech", "IN"),
  lv("stanza-living", "Stanza Living", "Consumer", "IN"),
  lv("nestaway", "Nestaway", "Consumer", "IN"),
  lv("nobroker", "NoBroker", "Consumer", "IN"),
  lv("magicbricks", "MagicBricks", "Consumer", "IN"),
  lv("housing", "Housing.com", "Consumer", "IN"),
  lv("droom", "Droom", "Consumer", "IN"),
  lv("cardekho", "CarDekho", "Consumer", "IN"),
  lv("bikes24", "Bikes24", "Consumer", "IN"),
  lv("pilot", "Pilot", "SaaS", "US"),
  lv("remote", "Remote", "SaaS", "US"),
  lv("deel", "Deel", "SaaS", "US"),
  lv("papayaglobal", "Papaya Global", "SaaS", "US"),
  lv("workato", "Workato", "SaaS", "US"),
  lv("calendly", "Calendly", "SaaS", "US"),
  lv("sendbird", "Sendbird", "SaaS", "US"),
  lv("contentful", "Contentful", "SaaS", "US"),
  lv("storyblok", "Storyblok", "SaaS", "US"),
  lv("sanity", "Sanity", "SaaS", "US"),
  lv("planetscale", "PlanetScale", "Infra", "US"),
  lv("cockroachlabs", "Cockroach Labs", "Infra", "US"),
  lv("timescale", "Timescale", "Infra", "US"),
  lv("clickhouse", "ClickHouse", "Infra", "US"),
  lv("singlestore", "SingleStore", "Infra", "US"),
  lv("paytm", "Paytm", "Fintech", "IN"),
];

const ASHBY: CompanyRecord[] = [
  ash("linear", "Linear", "SaaS"),
  ash("supabase", "Supabase", "SaaS"),
  ash("retool", "Retool", "SaaS"),
  ash("ramp", "Ramp", "Fintech"),
  ash("mercury", "Mercury", "Fintech"),
  ash("perplexity-ai", "Perplexity", "AI"),
  ash("dbtlabs", "dbt Labs", "SaaS"),
  ash("hex", "Hex", "SaaS"),
  ash("loom", "Loom", "SaaS"),
  ash("hightouch", "Hightouch", "SaaS"),
  ash("census", "Census", "SaaS"),
  ash("metabase", "Metabase", "SaaS"),
  ash("posthog", "PostHog", "SaaS"),
  ash("lago", "Lago", "SaaS"),
  ash("neon", "Neon", "Infra"),
  ash("turso", "Turso", "Infra"),
  ash("cal", "Cal.com", "SaaS"),
  ash("dub", "Dub.co", "SaaS"),
  ash("vanta", "Vanta", "SaaS"),
  ash("drata", "Drata", "SaaS"),
  ash("secureframe", "Secureframe", "SaaS"),
  ash("roboflow", "Roboflow", "AI"),
  ash("arize", "Arize AI", "AI"),
  ash("readwise", "Readwise", "SaaS"),
  ash("outerbase", "Outerbase", "Infra"),
  ash("trigger", "Trigger.dev", "SaaS"),
  ash("resend", "Resend", "SaaS"),
];

/** Avoid duplicate slugs when merging Ashby/Lever name collisions — prefer first occurrence. */
const SMART_RECRUITERS: CompanyRecord[] = [
  sr("IKEA", "IKEA"),
  sr("Booking.com", "Booking.com"),
  sr("Lidl", "Lidl"),
  sr("Skechers", "Skechers"),
  sr("Visa", "Visa"),
  sr("McDonalds", "McDonald's"),
  sr("Bosch", "Bosch"),
  sr("Siemens", "Siemens"),
  sr("SAP", "SAP"),
  sr("Thoughtworks", "Thoughtworks"),
  sr("GlobalLogic", "GlobalLogic"),
];

const WORKDAY: CompanyRecord[] = [
  wd("Walmart", "walmart", "https://walmart.wd5.myworkdayjobs.com/WalmartExternal"),
  wd("Adobe", "adobe", "https://adobe.wd5.myworkdayjobs.com/external_experienced"),
  wd("Oracle", "oracle", "https://oracle.wd1.myworkdayjobs.com/External_US"),
  wd("Workday", "workday-inc", "https://workday.wd5.myworkdayjobs.com/Workday"),
  wd("ServiceNow", "servicenow", "https://servicenow.wd5.myworkdayjobs.com/External"),
  wd("VMware", "vmware", "https://vmware.wd1.myworkdayjobs.com/VMware"),
  wd("OYO", "oyo", "https://oyo.wd3.myworkdayjobs.com/oyocareers"),
  wd("Zomato", "zomato", "https://zomato.wd3.myworkdayjobs.com/Zomato-Careers"),
  wd("Flipkart", "flipkart", "https://flipkart.wd3.myworkdayjobs.com/Flipkart_Careers"),
  wd("Infosys", "infosys", "https://infosys.wd3.myworkdayjobs.com/Infosys_Careers"),
  wd("Wipro", "wipro", "https://wipro.wd3.myworkdayjobs.com/Wipro_Careers"),
  wd("HCL", "hcl", "https://hcltech.wd3.myworkdayjobs.com/HCLTech"),
  wd("TCS", "tcs", "https://tcs.wd3.myworkdayjobs.com/TCS"),
];

const DIRECT: CompanyRecord[] = [
  dr("Google", "google", "https://careers.google.com/jobs/results/?q=product+manager&location=India", "BigTech", "US"),
  dr("Amazon", "amazon", "https://www.amazon.jobs/en/search?base_query=senior+product+manager&loc_query=India", "BigTech", "US"),
  dr("Microsoft", "microsoft", "https://jobs.careers.microsoft.com/", "BigTech", "US"),
  dr("PhonePe", "phonepe", "https://www.phonepe.com/careers/", "Fintech", "IN"),
  dr("Zerodha", "zerodha", "https://zerodha.com/careers/", "Fintech", "IN"),
  dr("Juspay", "juspay", "https://juspay.in/careers", "Fintech", "IN"),
  dr("Navi", "navi", "https://navi.com/careers", "Fintech", "IN"),
  dr("Zoho", "zoho", "https://careers.zohocorp.com/jobs/Careers", "SaaS", "IN"),
  dr("BharatPe", "bharatpe", "https://bharatpe.com/careers", "Fintech", "IN"),
  dr("Nykaa", "nykaa", "https://www.nykaa.com/careers", "Consumer", "IN"),
  dr("Lenskart", "lenskart", "https://www.lenskart.com/careers", "Consumer", "IN"),
];

function dedupeBySlug(records: CompanyRecord[]): CompanyRecord[] {
  const seen = new Set<string>();
  return records.filter((r) => {
    if (seen.has(r.slug)) return false;
    seen.add(r.slug);
    return true;
  });
}

export const REGISTRY_COMPANIES: CompanyRecord[] = dedupeBySlug([
  ...GREENHOUSE,
  ...LEVER,
  ...ASHBY,
  ...SMART_RECRUITERS,
  ...WORKDAY,
  ...DIRECT,
]);
