import type { Noun } from "@/lib/italian-coach/types";

export const nouns: Noun[] = [
  // —— Food & drink ——
  { id: "te", singular: "tè", plural: "tè", english: "tea", gender: "m" },
  { id: "caffe", singular: "caffè", plural: "caffè", english: "coffee", gender: "m" },
  { id: "acqua", singular: "acqua", plural: "acque", english: "water", gender: "f" },
  { id: "pizza", singular: "pizza", plural: "pizze", english: "pizza", gender: "f" },
  { id: "pane", singular: "pane", plural: "pani", english: "bread", gender: "m" },
  { id: "vino", singular: "vino", plural: "vini", english: "wine", gender: "m" },
  { id: "latte", singular: "latte", plural: "latti", english: "milk", gender: "m" },
  { id: "pasta", singular: "pasta", plural: "paste", english: "pasta", gender: "f" },
  { id: "mela", singular: "mela", plural: "mele", english: "apple", gender: "f" },
  { id: "formaggio", singular: "formaggio", plural: "formaggi", english: "cheese", gender: "m" },
  { id: "zucchero", singular: "zucchero", plural: "zuccheri", english: "sugar", gender: "m", articleSingular: "lo" },
  { id: "riso", singular: "riso", plural: "risi", english: "rice", gender: "m" },
  { id: "carne", singular: "carne", plural: "carni", english: "meat", gender: "f" },
  { id: "pesce", singular: "pesce", plural: "pesci", english: "fish", gender: "m" },
  { id: "frutta", singular: "frutta", plural: "frutte", english: "fruit", gender: "f" },
  { id: "verdura", singular: "verdura", plural: "verdure", english: "vegetables", gender: "f" },
  { id: "insalata", singular: "insalata", plural: "insalate", english: "salad", gender: "f" },
  { id: "gelato", singular: "gelato", plural: "gelati", english: "ice cream", gender: "m" },
  { id: "uovo", singular: "uovo", plural: "uova", english: "egg", gender: "m" },
  { id: "pollo", singular: "pollo", plural: "polli", english: "chicken", gender: "m" },
  { id: "birra", singular: "birra", plural: "birre", english: "beer", gender: "f" },
  { id: "succo", singular: "succo", plural: "succhi", english: "juice", gender: "m" },
  { id: "sale", singular: "sale", plural: "sali", english: "salt", gender: "m" },
  { id: "olio", singular: "olio", plural: "oli", english: "oil", gender: "m" },
  { id: "dolce", singular: "dolce", plural: "dolci", english: "dessert / sweet", gender: "m" },
  { id: "colazione", singular: "colazione", plural: "colazioni", english: "breakfast", gender: "f" },
  { id: "pranzo", singular: "pranzo", plural: "pranzi", english: "lunch", gender: "m" },
  { id: "cena", singular: "cena", plural: "cene", english: "dinner", gender: "f" },

  // —— Places ——
  { id: "casa", singular: "casa", plural: "case", english: "house / home", gender: "f" },
  { id: "scuola", singular: "scuola", plural: "scuole", english: "school", gender: "f" },
  { id: "citta", singular: "città", plural: "città", english: "city", gender: "f" },
  { id: "piazza", singular: "piazza", plural: "piazze", english: "square", gender: "f" },
  { id: "ristorante", singular: "ristorante", plural: "ristoranti", english: "restaurant", gender: "m" },
  { id: "ufficio", singular: "ufficio", plural: "uffici", english: "office", gender: "m" },
  { id: "mercato", singular: "mercato", plural: "mercati", english: "market", gender: "m" },
  { id: "giardino", singular: "giardino", plural: "giardini", english: "garden", gender: "m" },
  { id: "strada", singular: "strada", plural: "strade", english: "street", gender: "f" },
  { id: "stazione", singular: "stazione", plural: "stazioni", english: "station", gender: "f" },
  { id: "ospedale", singular: "ospedale", plural: "ospedali", english: "hospital", gender: "m" },
  { id: "farmacia", singular: "farmacia", plural: "farmacie", english: "pharmacy", gender: "f" },
  { id: "banca", singular: "banca", plural: "banche", english: "bank", gender: "f" },
  { id: "chiesa", singular: "chiesa", plural: "chiese", english: "church", gender: "f" },
  { id: "museo", singular: "museo", plural: "musei", english: "museum", gender: "m" },
  { id: "parco", singular: "parco", plural: "parchi", english: "park", gender: "m" },
  { id: "spiaggia", singular: "spiaggia", plural: "spiagge", english: "beach", gender: "f" },
  { id: "montagna", singular: "montagna", plural: "montagne", english: "mountain", gender: "f" },
  { id: "mare", singular: "mare", plural: "mari", english: "sea", gender: "m" },
  { id: "paese", singular: "paese", plural: "paesi", english: "country / village", gender: "m" },
  { id: "mondo", singular: "mondo", plural: "mondi", english: "world", gender: "m" },
  { id: "italia", singular: "Italia", plural: "Italia", english: "Italy", gender: "f" },
  { id: "albergo", singular: "albergo", plural: "alberghi", english: "hotel", gender: "m" },
  { id: "aeroporto", singular: "aeroporto", plural: "aeroporti", english: "airport", gender: "m" },
  { id: "treno", singular: "treno", plural: "treni", english: "train", gender: "m" },
  { id: "autobus", singular: "autobus", plural: "autobus", english: "bus", gender: "m" },
  { id: "negozio", singular: "negozio", plural: "negozi", english: "shop", gender: "m" },
  { id: "biblioteca", singular: "biblioteca", plural: "biblioteche", english: "library", gender: "f" },
  { id: "universita", singular: "università", plural: "università", english: "university", gender: "f" },

  // —— People & family ——
  { id: "amico", singular: "amico", plural: "amici", english: "friend (m)", gender: "m" },
  { id: "amica", singular: "amica", plural: "amiche", english: "friend (f)", gender: "f" },
  { id: "donna", singular: "donna", plural: "donne", english: "woman", gender: "f" },
  { id: "uomo", singular: "uomo", plural: "uomini", english: "man", gender: "m" },
  { id: "ragazzo", singular: "ragazzo", plural: "ragazzi", english: "boy / young man", gender: "m" },
  { id: "ragazza", singular: "ragazza", plural: "ragazze", english: "girl / young woman", gender: "f" },
  { id: "bambino", singular: "bambino", plural: "bambini", english: "child (m)", gender: "m" },
  { id: "famiglia", singular: "famiglia", plural: "famiglie", english: "family", gender: "f" },
  { id: "studente", singular: "studente", plural: "studenti", english: "student", gender: "m", articleSingular: "lo" },
  { id: "madre", singular: "madre", plural: "madri", english: "mother", gender: "f" },
  { id: "padre", singular: "padre", plural: "padri", english: "father", gender: "m" },
  { id: "figlio", singular: "figlio", plural: "figli", english: "son / child (m)", gender: "m" },
  { id: "figlia", singular: "figlia", plural: "figlie", english: "daughter", gender: "f" },
  { id: "fratello", singular: "fratello", plural: "fratelli", english: "brother", gender: "m" },
  { id: "sorella", singular: "sorella", plural: "sorelle", english: "sister", gender: "f" },
  { id: "marito", singular: "marito", plural: "mariti", english: "husband", gender: "m" },
  { id: "moglie", singular: "moglie", plural: "mogli", english: "wife", gender: "f" },
  { id: "nonno", singular: "nonno", plural: "nonni", english: "grandfather", gender: "m" },
  { id: "nonna", singular: "nonna", plural: "nonne", english: "grandmother", gender: "f" },
  { id: "dottore", singular: "dottore", plural: "dottori", english: "doctor", gender: "m" },
  { id: "professore", singular: "professore", plural: "professori", english: "professor / teacher", gender: "m" },
  { id: "persona", singular: "persona", plural: "persone", english: "person", gender: "f" },
  { id: "gente", singular: "gente", plural: "genti", english: "people", gender: "f" },

  // —— Objects & daily life ——
  { id: "libro", singular: "libro", plural: "libri", english: "book", gender: "m" },
  { id: "tavolo", singular: "tavolo", plural: "tavoli", english: "table", gender: "m" },
  { id: "sedia", singular: "sedia", plural: "sedie", english: "chair", gender: "f" },
  { id: "macchina", singular: "macchina", plural: "macchine", english: "car", gender: "f" },
  { id: "telefono", singular: "telefono", plural: "telefoni", english: "phone", gender: "m" },
  { id: "finestra", singular: "finestra", plural: "finestre", english: "window", gender: "f" },
  { id: "porta", singular: "porta", plural: "porte", english: "door", gender: "f" },
  { id: "computer", singular: "computer", plural: "computer", english: "computer", gender: "m" },
  { id: "televisione", singular: "televisione", plural: "televisioni", english: "television", gender: "f" },
  { id: "penna", singular: "penna", plural: "penne", english: "pen", gender: "f" },
  { id: "carta", singular: "carta", plural: "carte", english: "paper / card", gender: "f" },
  { id: "soldi", singular: "soldi", plural: "soldi", english: "money", gender: "m" },
  { id: "chiave", singular: "chiave", plural: "chiavi", english: "key", gender: "f" },
  { id: "luce", singular: "luce", plural: "luci", english: "light", gender: "f" },
  { id: "letto", singular: "letto", plural: "letti", english: "bed", gender: "m" },
  { id: "bagno", singular: "bagno", plural: "bagni", english: "bathroom", gender: "m" },
  { id: "cucina", singular: "cucina", plural: "cucine", english: "kitchen", gender: "f" },
  { id: "camera", singular: "camera", plural: "camere", english: "room / bedroom", gender: "f" },
  { id: "vestito", singular: "vestito", plural: "vestiti", english: "dress / clothes", gender: "m" },
  { id: "scarpe", singular: "scarpa", plural: "scarpe", english: "shoes", gender: "f" },
  { id: "orologio", singular: "orologio", plural: "orologi", english: "clock / watch", gender: "m" },

  // —— Nature & animals ——
  { id: "sole", singular: "sole", plural: "soli", english: "sun", gender: "m" },
  { id: "luna", singular: "luna", plural: "lune", english: "moon", gender: "f" },
  { id: "cielo", singular: "cielo", plural: "cieli", english: "sky", gender: "m" },
  { id: "albero", singular: "albero", plural: "alberi", english: "tree", gender: "m" },
  { id: "fiore", singular: "fiore", plural: "fiori", english: "flower", gender: "m" },
  { id: "animale", singular: "animale", plural: "animali", english: "animal", gender: "m" },
  { id: "cane", singular: "cane", plural: "cani", english: "dog", gender: "m" },
  { id: "gatto", singular: "gatto", plural: "gatti", english: "cat", gender: "m" },

  // —— Body ——
  { id: "testa", singular: "testa", plural: "teste", english: "head", gender: "f" },
  { id: "mano", singular: "mano", plural: "mani", english: "hand", gender: "f" },
  { id: "occhio", singular: "occhio", plural: "occhi", english: "eye", gender: "m" },
  { id: "cuore", singular: "cuore", plural: "cuori", english: "heart", gender: "m" },
  { id: "corpo", singular: "corpo", plural: "corpi", english: "body", gender: "m" },

  // —— Time & abstract ——
  { id: "giorno", singular: "giorno", plural: "giorni", english: "day", gender: "m" },
  { id: "notte", singular: "notte", plural: "notti", english: "night", gender: "f" },
  { id: "mattina", singular: "mattina", plural: "mattine", english: "morning", gender: "f" },
  { id: "sera", singular: "sera", plural: "sere", english: "evening", gender: "f" },
  { id: "anno", singular: "anno", plural: "anni", english: "year", gender: "m" },
  { id: "tempo", singular: "tempo", plural: "tempi", english: "time / weather", gender: "m" },
  { id: "vita", singular: "vita", plural: "vite", english: "life", gender: "f" },
  { id: "lavoro", singular: "lavoro", plural: "lavori", english: "work / job", gender: "m" },
  { id: "amore", singular: "amore", plural: "amori", english: "love", gender: "m" },
  { id: "parola", singular: "parola", plural: "parole", english: "word", gender: "f" },
  { id: "idea", singular: "idea", plural: "idee", english: "idea", gender: "f" },
  { id: "problema", singular: "problema", plural: "problemi", english: "problem", gender: "m" },
  { id: "domanda", singular: "domanda", plural: "domande", english: "question", gender: "f" },
  { id: "risposta", singular: "risposta", plural: "risposte", english: "answer", gender: "f" },
  { id: "storia", singular: "storia", plural: "storie", english: "story / history", gender: "f" },
  { id: "musica", singular: "musica", plural: "musiche", english: "music", gender: "f" },
  { id: "lingua", singular: "lingua", plural: "lingue", english: "language / tongue", gender: "f" },
  { id: "nome", singular: "nome", plural: "nomi", english: "name", gender: "m" },
  { id: "momento", singular: "momento", plural: "momenti", english: "moment", gender: "m" },
  { id: "cosa", singular: "cosa", plural: "cose", english: "thing", gender: "f" },
  { id: "posto", singular: "posto", plural: "posti", english: "place / spot", gender: "m" },
];
