import type { Adjective, Connector, TimeWord } from "@/lib/italian-coach/types";

export const adjectives: Adjective[] = [
  { id: "bello", english: "beautiful", m_sg: "bello", f_sg: "bella", m_pl: "belli", f_pl: "belle" },
  { id: "brutto", english: "ugly", m_sg: "brutto", f_sg: "brutta", m_pl: "brutti", f_pl: "brutte" },
  { id: "grande", english: "big", m_sg: "grande", f_sg: "grande", m_pl: "grandi", f_pl: "grandi" },
  { id: "piccolo", english: "small", m_sg: "piccolo", f_sg: "piccola", m_pl: "piccoli", f_pl: "piccole" },
  { id: "buono", english: "good", m_sg: "buono", f_sg: "buona", m_pl: "buoni", f_pl: "buone" },
  { id: "cattivo", english: "bad", m_sg: "cattivo", f_sg: "cattiva", m_pl: "cattivi", f_pl: "cattive" },
  { id: "alto", english: "tall / high", m_sg: "alto", f_sg: "alta", m_pl: "alti", f_pl: "alte" },
  { id: "basso", english: "short / low", m_sg: "basso", f_sg: "bassa", m_pl: "bassi", f_pl: "basse" },
  { id: "vecchio", english: "old", m_sg: "vecchio", f_sg: "vecchia", m_pl: "vecchi", f_pl: "vecchie" },
  { id: "nuovo", english: "new", m_sg: "nuovo", f_sg: "nuova", m_pl: "nuovi", f_pl: "nuove" },
  { id: "caldo", english: "hot", m_sg: "caldo", f_sg: "calda", m_pl: "caldi", f_pl: "calde" },
  { id: "freddo", english: "cold", m_sg: "freddo", f_sg: "fredda", m_pl: "freddi", f_pl: "fredde" },
  { id: "felice", english: "happy", m_sg: "felice", f_sg: "felice", m_pl: "felici", f_pl: "felici" },
  { id: "triste", english: "sad", m_sg: "triste", f_sg: "triste", m_pl: "tristi", f_pl: "tristi" },
  { id: "importante", english: "important", m_sg: "importante", f_sg: "importante", m_pl: "importanti", f_pl: "importanti" },
  { id: "facile", english: "easy", m_sg: "facile", f_sg: "facile", m_pl: "facili", f_pl: "facili" },
  { id: "difficile", english: "difficult", m_sg: "difficile", f_sg: "difficile", m_pl: "difficili", f_pl: "difficili" },
  { id: "veloce", english: "fast", m_sg: "veloce", f_sg: "veloce", m_pl: "veloci", f_pl: "veloci" },
  { id: "lento", english: "slow", m_sg: "lento", f_sg: "lenta", m_pl: "lenti", f_pl: "lente" },
  { id: "giovane", english: "young", m_sg: "giovane", f_sg: "giovane", m_pl: "giovani", f_pl: "giovani" },
  { id: "ricco", english: "rich", m_sg: "ricco", f_sg: "ricca", m_pl: "ricchi", f_pl: "ricche" },
  { id: "povero", english: "poor", m_sg: "povero", f_sg: "povera", m_pl: "poveri", f_pl: "povere" },
  { id: "stanco", english: "tired", m_sg: "stanco", f_sg: "stanca", m_pl: "stanchi", f_pl: "stanche" },
  { id: "affamato", english: "hungry", m_sg: "affamato", f_sg: "affamata", m_pl: "affamati", f_pl: "affamate" },
  { id: "pronto", english: "ready", m_sg: "pronto", f_sg: "pronta", m_pl: "pronti", f_pl: "pronte" },
  { id: "sicuro", english: "sure / safe", m_sg: "sicuro", f_sg: "sicura", m_pl: "sicuri", f_pl: "sicure" },
  { id: "vero", english: "true", m_sg: "vero", f_sg: "vera", m_pl: "veri", f_pl: "vere" },
  { id: "falso", english: "false", m_sg: "falso", f_sg: "falsa", m_pl: "falsi", f_pl: "false" },
  { id: "italiano", english: "Italian", m_sg: "italiano", f_sg: "italiana", m_pl: "italiani", f_pl: "italiane" },
  { id: "inglese", english: "English", m_sg: "inglese", f_sg: "inglese", m_pl: "inglesi", f_pl: "inglesi" },
];

export const timeWords: TimeWord[] = [
  { id: "oggi", word: "oggi", english: "today" },
  { id: "domani", word: "domani", english: "tomorrow" },
  { id: "ieri", word: "ieri", english: "yesterday" },
  { id: "ora", word: "ora", english: "now" },
  { id: "adesso", word: "adesso", english: "right now" },
  { id: "sempre", word: "sempre", english: "always" },
  { id: "mai", word: "mai", english: "never" },
  { id: "spesso", word: "spesso", english: "often" },
  { id: "presto", word: "presto", english: "early / soon" },
  { id: "tardi", word: "tardi", english: "late" },
  { id: "molto", word: "molto", english: "very / a lot" },
  { id: "poco", word: "poco", english: "little / few" },
  { id: "subito", word: "subito", english: "immediately" },
  { id: "ancora", word: "ancora", english: "still / again" },
  { id: "gia", word: "già", english: "already" },
  { id: "poi", word: "poi", english: "then / later" },
  { id: "prima", word: "prima", english: "before / first" },
  { id: "dopo", word: "dopo", english: "after / later" },
  { id: "settimana", word: "settimana", english: "week" },
  { id: "mese", word: "mese", english: "month" },
];

export const connectors: Connector[] = [
  { id: "e", word: "e", english: "and" },
  { id: "ma", word: "ma", english: "but" },
  { id: "o", word: "o", english: "or" },
  { id: "perche", word: "perché", english: "because" },
  { id: "con", word: "con", english: "with" },
  { id: "senza", word: "senza", english: "without" },
  { id: "per", word: "per", english: "for" },
  { id: "anche", word: "anche", english: "also" },
  { id: "se", word: "se", english: "if" },
  { id: "quando", word: "quando", english: "when" },
  { id: "di", word: "di", english: "of / from" },
  { id: "a", word: "a", english: "to / at" },
  { id: "da", word: "da", english: "from / by" },
  { id: "in", word: "in", english: "in" },
  { id: "su", word: "su", english: "on / about" },
  { id: "tra", word: "tra", english: "between / among" },
  { id: "fra", word: "fra", english: "between / among" },
  { id: "come", word: "come", english: "how / like" },
  { id: "che", word: "che", english: "that / which" },
  { id: "quindi", word: "quindi", english: "therefore" },
  { id: "pero", word: "però", english: "however" },
  { id: "mentre", word: "mentre", english: "while" },
  { id: "prima_di", word: "prima di", english: "before" },
  { id: "dopo_di", word: "dopo di", english: "after" },
];
