import { verbAre, verbEre, verbIre, verbIreSc } from "@/lib/italian-coach/verb-helpers";
import type { Verb } from "@/lib/italian-coach/types";

/** Irregular / high-frequency verbs (hand-authored) */
const irregular: Verb[] = [
  {
    id: "essere",
    infinitive: "essere",
    english: "to be",
    present: { io: "sono", tu: "sei", lui_lei: "è", noi: "siamo", voi: "siete", loro: "sono" },
  },
  {
    id: "avere",
    infinitive: "avere",
    english: "to have",
    present: { io: "ho", tu: "hai", lui_lei: "ha", noi: "abbiamo", voi: "avete", loro: "hanno" },
  },
  {
    id: "volere",
    infinitive: "volere",
    english: "to want",
    present: { io: "voglio", tu: "vuoi", lui_lei: "vuole", noi: "vogliamo", voi: "volete", loro: "vogliono" },
  },
  {
    id: "potere",
    infinitive: "potere",
    english: "can / to be able",
    present: { io: "posso", tu: "puoi", lui_lei: "può", noi: "possiamo", voi: "potete", loro: "possono" },
  },
  {
    id: "dovere",
    infinitive: "dovere",
    english: "must / to have to",
    present: { io: "devo", tu: "devi", lui_lei: "deve", noi: "dobbiamo", voi: "dovete", loro: "devono" },
  },
  {
    id: "sapere",
    infinitive: "sapere",
    english: "to know (facts)",
    present: { io: "so", tu: "sai", lui_lei: "sa", noi: "sappiamo", voi: "sapete", loro: "sanno" },
  },
  {
    id: "andare",
    infinitive: "andare",
    english: "to go",
    present: { io: "vado", tu: "vai", lui_lei: "va", noi: "andiamo", voi: "andate", loro: "vanno" },
  },
  {
    id: "venire",
    infinitive: "venire",
    english: "to come",
    present: { io: "vengo", tu: "vieni", lui_lei: "viene", noi: "veniamo", voi: "venite", loro: "vengono" },
  },
  {
    id: "fare",
    infinitive: "fare",
    english: "to do / make",
    present: { io: "faccio", tu: "fai", lui_lei: "fa", noi: "facciamo", voi: "fate", loro: "fanno" },
  },
  {
    id: "dire",
    infinitive: "dire",
    english: "to say / tell",
    present: { io: "dico", tu: "dici", lui_lei: "dice", noi: "diciamo", voi: "dite", loro: "dicono" },
  },
  {
    id: "vedere",
    infinitive: "vedere",
    english: "to see",
    present: { io: "vedo", tu: "vedi", lui_lei: "vede", noi: "vediamo", voi: "vedete", loro: "vedono" },
  },
  {
    id: "bere",
    infinitive: "bere",
    english: "to drink",
    present: { io: "bevo", tu: "bevi", lui_lei: "beve", noi: "beviamo", voi: "bevete", loro: "bevono" },
  },
  {
    id: "leggere",
    infinitive: "leggere",
    english: "to read",
    present: { io: "leggo", tu: "leggi", lui_lei: "legge", noi: "leggiamo", voi: "leggete", loro: "leggono" },
  },
  {
    id: "scrivere",
    infinitive: "scrivere",
    english: "to write",
    present: { io: "scrivo", tu: "scrivi", lui_lei: "scrive", noi: "scriviamo", voi: "scrivete", loro: "scrivono" },
  },
  {
    id: "dare",
    infinitive: "dare",
    english: "to give",
    present: { io: "do", tu: "dai", lui_lei: "dà", noi: "diamo", voi: "date", loro: "danno" },
  },
  {
    id: "stare",
    infinitive: "stare",
    english: "to stay / be (state)",
    present: { io: "sto", tu: "stai", lui_lei: "sta", noi: "stiamo", voi: "state", loro: "stanno" },
  },
  {
    id: "uscire",
    infinitive: "uscire",
    english: "to go out",
    present: { io: "esco", tu: "esci", lui_lei: "esce", noi: "usciamo", voi: "uscite", loro: "escono" },
  },
  {
    id: "rimanere",
    infinitive: "rimanere",
    english: "to remain / stay",
    present: { io: "rimango", tu: "rimani", lui_lei: "rimane", noi: "rimaniamo", voi: "rimanete", loro: "rimangono" },
  },
  {
    id: "prendere",
    infinitive: "prendere",
    english: "to take / get",
    present: { io: "prendo", tu: "prendi", lui_lei: "prende", noi: "prendiamo", voi: "prendete", loro: "prendono" },
  },
  {
    id: "mettere",
    infinitive: "mettere",
    english: "to put",
    present: { io: "metto", tu: "metti", lui_lei: "mette", noi: "mettiamo", voi: "mettete", loro: "mettono" },
  },
  {
    id: "aprire",
    infinitive: "aprire",
    english: "to open",
    present: { io: "apro", tu: "apri", lui_lei: "apre", noi: "apriamo", voi: "aprite", loro: "aprono" },
  },
  {
    id: "chiudere",
    infinitive: "chiudere",
    english: "to close",
    present: { io: "chiudo", tu: "chiudi", lui_lei: "chiude", noi: "chiudiamo", voi: "chiudete", loro: "chiudono" },
  },
  {
    id: "correre",
    infinitive: "correre",
    english: "to run",
    present: { io: "corro", tu: "corri", lui_lei: "corre", noi: "corriamo", voi: "correte", loro: "corrono" },
  },
  {
    id: "conoscere",
    infinitive: "conoscere",
    english: "to know (people/places)",
    present: { io: "conosco", tu: "conosci", lui_lei: "conosce", noi: "conosciamo", voi: "conoscete", loro: "conoscono" },
  },
  {
    id: "credere",
    infinitive: "credere",
    english: "to believe",
    present: { io: "credo", tu: "credi", lui_lei: "crede", noi: "crediamo", voi: "credete", loro: "credono" },
  },
];

/** Regular verbs generated from stems */
const regular: Verb[] = [
  verbAre("mangiare", "mangiare", "mangi", "to eat"),
  verbAre("parlare", "parlare", "parl", "to speak"),
  verbAre("lavorare", "lavorare", "lavor", "to work"),
  verbAre("studiare", "studiare", "studi", "to study"),
  verbAre("comprare", "comprare", "compr", "to buy"),
  verbAre("amare", "amare", "am", "to love"),
  verbAre("pensare", "pensare", "pens", "to think"),
  verbAre("aspettare", "aspettare", "aspett", "to wait"),
  verbAre("cercare", "cercare", "cerc", "to look for"),
  verbAre("trovare", "trovare", "trov", "to find"),
  verbAre("portare", "portare", "port", "to bring / wear"),
  verbAre("chiamare", "chiamare", "chiam", "to call"),
  verbAre("ascoltare", "ascoltare", "ascolt", "to listen"),
  verbAre("guardare", "guardare", "guard", "to watch / look"),
  verbAre("aiutare", "aiutare", "aiut", "to help"),
  verbAre("imparare", "imparare", "impar", "to learn"),
  verbAre("insegnare", "insegnare", "insegn", "to teach"),
  verbAre("viaggiare", "viaggiare", "viagg", "to travel"),
  verbAre("guidare", "guidare", "guid", "to drive"),
  verbAre("giocare", "giocare", "gioc", "to play"),
  verbAre("cucinare", "cucinare", "cucin", "to cook"),
  verbAre("ballare", "ballare", "ball", "to dance"),
  verbAre("cantare", "cantare", "cant", "to sing"),
  verbAre("camminare", "camminare", "cammin", "to walk"),
  verbAre("nuotare", "nuotare", "nuot", "to swim"),
  verbIre("pulire", "pulire", "pul", "to clean"),
  verbAre("usare", "usare", "us", "to use"),
  verbAre("provare", "provare", "prov", "to try"),
  verbAre("cominciare", "cominciare", "cominci", "to begin"),
  verbIre("finire", "finire", "fin", "to finish"),
  verbAre("pagare", "pagare", "pag", "to pay"),
  verbAre("costare", "costare", "cost", "to cost"),
  verbAre("mandare", "mandare", "mand", "to send"),
  verbAre("tornare", "tornare", "torn", "to return"),
  verbAre("entrare", "entrare", "entr", "to enter"),
  verbAre("passare", "passare", "pass", "to pass / spend (time)"),
  verbAre("abitare", "abitare", "abit", "to live (reside)"),
  verbAre("lasciare", "lasciare", "lasc", "to leave / let"),
  verbAre("domandare", "domandare", "domand", "to ask"),
  verbAre("rispondere", "rispondere", "rispond", "to answer"),
  verbAre("spiegare", "spiegare", "spieg", "to explain"),
  verbAre("ricordare", "ricordare", "ricord", "to remember"),
  verbAre("dimenticare", "dimenticare", "dimentic", "to forget"),
  verbAre("sperare", "sperare", "sper", "to hope"),
  verbAre("desiderare", "desiderare", "desider", "to wish / desire"),
  verbEre("vivere", "vivere", "viv", "to live"),
  verbEre("vendere", "vendere", "vend", "to sell"),
  verbEre("ricevere", "ricevere", "ricev", "to receive"),
  verbEre("perdere", "perdere", "perd", "to lose"),
  verbEre("cadere", "cadere", "cad", "to fall"),
  verbEre("ridere", "ridere", "rid", "to laugh"),
  verbEre("piangere", "piangere", "piang", "to cry"),
  verbEre("sentire", "sentire", "sent", "to feel / hear"),
  verbEre("offrire", "offrire", "offr", "to offer"),
  verbEre("decidere", "decidere", "decid", "to decide"),
  verbEre("chiudere", "chiudere", "chiud", "to close"),
  verbIre("dormire", "dormire", "dorm", "to sleep"),
  verbIre("partire", "partire", "part", "to leave / depart"),
  verbIre("servire", "servire", "serv", "to serve"),
  verbIreSc("capire", "capire", "cap", "to understand"),
  verbIreSc("preferire", "preferire", "prefer", "to prefer"),
  verbIreSc("spedire", "spedire", "sped", "to send (mail)"),
];

// Remove duplicate chiudere from regular (already in irregular)
const regularFiltered = regular.filter((v) => !irregular.some((i) => i.id === v.id));

export const verbs: Verb[] = [...irregular, ...regularFiltered];
